.codecov.yaml, cmd/orb-server/main.go, go.mod, go.sum, pkg/api/txn/model.go, pkg/context/txnclient/client.go, pkg/httpserver/server.go, pkg/mocks/protocol.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/txngraph/graph.go, pkg/txngraph/graph_test.go, pkg/txnprocessor/txnprocessor.go, pkg/txnprocessor/txnprocessor_test.go
Txn Graph:
-- add get did transactions to txn graph.
Txn Processor:
-- add retrieving all orb transactions for did and check them against operations in operation store.
Closes #13
=> feat: Add get orb txns for did in txn graph

.gitignore, pkg/activitypub/vocab/contextproperty.go, pkg/activitypub/vocab/contextproperty_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/typeproperty.go, pkg/activitypub/vocab/typeproperty_test.go, pkg/activitypub/vocab/urlproperty.go, pkg/activitypub/vocab/urlproperty_test.go, pkg/activitypub/vocab/util.go, pkg/activitypub/vocab/util_test.go, pkg/activitypub/vocab/vocab.go, pkg/activitypub/vocab/vocab_test.go
Defined the various types and properties for ActivityPub. Also implemented a basic Object type.
closes #26
=> feat: Define the basic ActivityPub vocabulary

pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/util_test.go
The value of the 'object' property can be an IRI (URL) or another embedded ActivityPub object.
closes #29
=> feat: Implemented ActivityPub 'object' property

pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/contextproperty.go, pkg/activitypub/vocab/contextproperty_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/typeproperty.go, pkg/activitypub/vocab/typeproperty_test.go, pkg/activitypub/vocab/urlproperty.go, pkg/activitypub/vocab/urlproperty_test.go
ActivityPub properties may now be accessed without a check for nil. For example:
isCreate := activity.Type().Is(TypeCreate)
Even if activity.Type() returns nil, the above will return false without a panic.
closes #46
=> feat: Don't require check for nil on ActivityPub properties

pkg/activitypub/store/memstore/iterator.go, pkg/activitypub/store/memstore/iterator_test.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/store/spi/spi.go, pkg/activitypub/store/spi/spi_test.go
This commit defines the ActivityPub store service provider interface and also implements an in-memory store.
closes #52
=> feat: Defined ActivityPub SPI and implemented in-memory store

pkg/activitypub/service/mocks/mockpubsub.go, pkg/activitypub/service/mocks/mockundeliverablehandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/outbox/redelivery/redelivery.go, pkg/activitypub/service/outbox/redelivery/redelivery_test.go, pkg/activitypub/service/spi/spi.go
Implemented an outbox for ActivityPub messages. The outbox sends an HTTP message with an activity and monitors whether or not the message was sent. If an error occurs then it attempts to redeliver the message (according to redelivery config).
closes #55
=> feat: Implemented ActivityPub Outbox

pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mempubsub/mempubsub.go, pkg/activitypub/service/mempubsub/mempubsub_test.go
Implemented an in-memory Publisher-Subscriber that supports the Watermill Subscriber and Publisher interfaces. This Publisher-Subscriber may later be replaced by a persistent message queue, such as RabbitMQ or Kafka.
closes #60
=> feat: In-memory publisher/subscriber

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/activityhandler.gen.go, pkg/activitypub/service/mocks/mocksubscriber.go, pkg/activitypub/service/mocks/mockundeliverablehandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go
Implemented an ActivityPub service that encapsulates an inbox and outbox. The service allow clients to post messages to the outbox and register for notifications of inbound activities. The service provides an activity handler to process the activities. Currently only a skeleton implementation is provided for the 'Create' activity. Future commits will provide implementations for all activities.
closes #56
=> feat: ActivityPub service

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/mocks/mockanchorcredhandler.go, pkg/activitypub/service/mocks/mocksubscriber.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go, pkg/activitypub/vocab/contextproperty.go, pkg/activitypub/vocab/contextproperty_test.go, pkg/activitypub/vocab/typeproperty.go, pkg/activitypub/vocab/typeproperty_test.go
Implemented a handler for the 'Create' activity which invokes an 'anchor credential handler' to handle the new anchor credential.
Also implemented the String() function on ContextProperty and TypeProperty to make logs more readable.
closes #68
=> feat: ActivityPub handler for 'Create' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/mocks/activities.go, pkg/activitypub/service/mocks/mockfollowerauth.go, pkg/activitypub/service/mocks/mockoutbox.go, pkg/activitypub/service/mocks/mocksubscriber.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go, pkg/activitypub/store/memstore/memstore.go
Implemented a handler for the ActivityPub 'Follow' activity. An authorization handler is 'asked' if the service should accept or reject the follow request. If accepted, the handler posts an 'Accept' activity to the requesting actor and adds the actor to the list of followers; otherwise a 'Reject' activity is posted.
closes #69
=> feat: Handler for 'Follow' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go
Implemented a handler for the ActivityPub 'Accept' activity. The handler adds the actor to the service's 'following' list and notifies subscribers of the activity.
closes #70
=> feat: Handler for the ActivityPub 'Accept' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/service_test.go
Implemented a handler for the ActivityPub 'Reject' activity. The handler should notify subscribers of the activity.
closes #71
=> feat: Handler for the ActivityPub 'Reject' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/service_test.go
Implemented a handler for the ActivityPub 'Announce' activity. The handler for the 'Create' activity posts an 'Announce' activity to the service's followers. The 'Announce' handler invokes the registered 'AnchorCredentialHandler' with the announced anchor credential.
closes #67
=> feat: Handler for the ActivityPub 'Announce' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/mockwitnesspub.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go
Implemented a handler for the ActivityPub 'Offer' activity. The handler invokes a 'witness' handler with the embedded anchor credential so that it may generate a proof. If successful, the handler posts a 'Like' activity with the proofs back to the actor (requestor). The handler also adds the activity to the service's 'liked' list.
closes #72
=> feat: Handler for the ActivityPub 'Offer' activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/mocks/mockwitnesshandler.go, pkg/activitypub/service/service.go, pkg/activitypub/service/spi/spi.go
The Offer handler responds with a 'Like' activity and the start and end times were set incorrectly. This commit changes the end time to be the current server time plus a configurable delay.
Also, the Offer activity is rejected if the offer has already expired (according to the endTime in the Offer activity).
closes #81
=> fix: Offer handler responds with incorrect start and end time in Like activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/mocks/mockproofhandler.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go
Implemented a handler for the ActivityPub 'Like' (endorse) activity. The handler invokes a 'proof' handler with the embedded proof so that it may handle the endorsed transaction. The handler also adds the 'Like' activity to the service's 'likes' list.
closes #73
=> feat: Handler for 'Like' activity

pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber_test.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go
Implemented a Watermill HTTP subscriber that may integrate with an existing HTTP server. This HTTP subscriber exposes a handler that can be registered with Orb's existing HTTP server. All REST endpoints may now be served from the same address/port.
closes #84
=> feat: HTTP Subscriber for Watermill

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph.go, pkg/anchor/graph/graph_test.go, pkg/anchor/proofs/proofs.go, pkg/anchor/proofs/proofs_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/didtxnref/memdidtxnref/refs.go, pkg/didtxnref/memdidtxnref/refs_test.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go
Anchor Writer must:
- request proofs for anchored credential from proof handler
- listen for witnessed anchored credential
- save witnessed anchored credentials to anchored credentials store
Also, add reference for create operation to previous transactions in anchor credential (it will be empty string)
Closes #107
=> feat: Listener for witnessed anchored credential

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/go.mod, test/bdd/go.sum
This list contains anchor origins for all dids in the Sidetree batch. Create and recover operations have anchor origins referenced in operation while for update and deactivate  we have to 'resolve' did in order to figure out anchor origin.
Closes #109
=> feat: Assemble witness list for Sidetree batch

cmd/orb-server/startcmd/start.go, pkg/anchor/proofs/proofs.go, pkg/anchor/proofs/proofs_test.go
There is no need for additional server configuration parameter. System witness list is an activity pub collection that is configured as activityPubURL + "/server/orb/witnesses". Add this 'system' witness list to the list of witnesses collected from Sidetree batch before creating an ActivityPub offer.
Closes #114
=> chore: Add system witness list

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/followershandler.go, pkg/activitypub/resthandler/followershandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/httpserver/server.go
Added a REST endpoint that returns a service's followers as a Collection or CollectionPage type. If the request does not include a 'page' parameter then a 'Collection' is returned that specifies the first and last page of the followers. If the request contains a 'page=true' parameter then a 'CollectionPage' is returned containing the IRI's of the followers for that page, along with the URLs of the previous and next page.
closes #95
=> feat: '/followers' REST endpoint

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/followhandler.go, pkg/activitypub/resthandler/followhandler_test.go, pkg/activitypub/resthandler/resthandler.go
Added a REST endpoint that returns the URIs that a service is following as a Collection or CollectionPage type. If the request does not include a 'page' parameter then a 'Collection' is returned that specifies the first and last page of the following list. If the request contains a 'page=true' parameter then a 'CollectionPage' is returned containing the IRI's of the list of 'following' for that page, along with the URLs of the previous and next page.
closes #96
=> feat: '/following' REST endpoint

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objecttype_test.go, pkg/anchor/graph/graph.go, pkg/anchor/graph/graph_test.go, pkg/anchor/proofs/proofs_test.go, pkg/anchor/txn/model.go, pkg/anchor/util/anchordata.go, pkg/anchor/util/anchordata_test.go, pkg/anchor/util/util_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
- "anchorString" will be split into "coreIndex" and "operationCount"
- "previousTransactions" will be renamed to "previousAnchors"
Closes #122
=> chore: Redefine/rename anchor credential subject fields

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/followhandler.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/store/storeutil/storeutil.go, pkg/activitypub/vocab/collection.go
Added REST endpoints that return the activities in the service's inbox and outbox as an OrderedCollection or OrderedCollectionPage type. If the request does not include a 'page' parameter then an 'OrderedCollection' is returned that specifies the first and last page of the inbox or outbox. The first page contains the most recent activities. If the request contains a 'page=true' parameter then an 'OrderedCollectionPage' is returned containing the activities for that page, along with the URLs of the previous and next page.
closes #93
closes #94
=> feat: Implemented '/outbox' and '/inbox' REST endpoints

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go
Added REST endpoints that return a service's witnesses as well as the URIs that the local service is witnessing. If the request does not include a 'page' parameter then a 'Collection' is returned that specifies the first and last page of the witnesses/witnessing. If the request contains a 'page=true' parameter then a 'CollectionPage' is returned containing the witnesses/witnessing URIs for that page, along with the URIs of the previous and next page.
closes #97
closes #98
=> feat: Implemented '/witnesses' and '/witnessing' REST endpoints

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go
Added a REST endpoint that returns the URIs of the objects that the service 'liked' as an OrderedCollection or OrderedCollectionPage type. If the request does not include a 'page' parameter then an 'OrderedCollection' is returned that specifies the first and last page of the objects that were liked. The most recent 'liked' objects are in the first page. If the request contains a 'page=true' parameter then an 'OrderedCollectionPage' is returned containing the IRI's of the liked for that page, along with the previous and next page.
closes #100
=> feat:  '/liked' REST endpoint

pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchorcredreftype.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab.go
The CAS object type has been renamed to 'ContentAddressedStorage' and the anchor credential reference target now has a resolvable 'id' as well as a 'cid' property.
closes #125
=> chore: Changed object type 'Cas' to 'ContentAddressedStorage' and added 'cid' property to target

pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/store/memstore/iterator_test.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/actortype_test.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/collection_test.go, pkg/activitypub/vocab/collectionpage_test.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/objecttype_test.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab_test.go, pkg/internal/testutil/testutil.go
Moved common testing utilities to the testutil package so that they aren't replicated in multiple packages.
closes #135
=> refactor: Move common testing functions into testutil

pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/vocab/actortype.go, pkg/activitypub/vocab/actortype_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go
Removed 'likes' from the actor since 'likes' is a property of the object that was 'liked'. Similarly, 'shares' was removed from the actor since 'shares' is a property of the object that was shared (announced).
closes #139
=> fix: Remove 'likes' and 'shares' from the actor

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/activitystore.gen.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/store/spi/spi.go
The ActivityPub storage can now store references from any object (not just actors) to a collection of activities. Activities are stored in a single place and the inbox and outbox are collections of references to the activities.
closes #143
=> refactor: Added support for activity references from any object

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go
The ActivityPub REST handler now supports using the object ID contained in the URL path. For example:
https://sally.example.com/transactions/d607506e-6964-4991-a19f-674952380760/shares
where ID=d607506e-6964-4991-a19f-674952380760
closes #145
=> feat: Added support for using object ID contained in URL

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go
Added a 'likes' endpoint that returns an object's Like activities and a 'shares' endpoint that returns the object's Announce activities. The ID of the object is specified in the URL.
closes #99
closes #101
=> feat: 'likes' and 'shares' REST endpoints

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go
In order to be consistent with the 'likes' REST endpoint, the 'Liked' activities are now returned in 'liked' requests.
closes #147
=> fix: Return 'Like' activities in 'liked' REST endpoint

pkg/activitypub/client/client.go, pkg/activitypub/client/client_test.go, pkg/activitypub/client/util.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go
If the 'to' field contains the IRI of a collection or ordered collection then the individual URIs are resolved and the activity is published to each of the URIs.
closes #137
=> feat: Intelligent endpoint resolution for ActivityPub 'to' property

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go
When an anchor credential is announced, the anchor credential's 'shares' list is updated with the 'Announce' activity.
closes #129
=> fix: Add 'shares' to anchor credential when announced

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go
The REST handler for '/services' now constructs a service using configuration parameters from the local server as opposed to retrieving it from storage.
closes #166
=> fix: REST handler for '/services' returns dynamically constructed service

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/service/inbox/inbox.go, test/bdd/features/activitypub.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/testdata/follow_activity.json
Added a BDD test for the follow/accept flows, as well as a test to retrieve the service. Also:
- Added external-endpoint as a startup parameter. This endpoint is used to construct the ID of the service (actor).
- Added another Orb node to Docker so that inter-process communincation may be tested.
closes #57
=> test: ActivityPub BDD tests: follow/accept

pkg/activitypub/resthandler/activityhandler.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/testdata/create_activity.json
Added BDD test for the ActivityPub service for the create/announce flow.
closes #168
=> test: ActivityPub BDD tests: create/announce

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph.go, pkg/protocolversion/versions/v1_0/factory/factory.go, test/bdd/bddtests_test.go, test/bdd/fixtures/docker-compose.yml
Fix race issue related to creating master lock. Both servers were creating master lock in the same database during start-up which caused issues after re-start. 
Quick fix (this PR) is done by writing to different database but this will be a problem once we start using both servers for DIDs. 
Intermediate fix can be done by staggering server starts and proper fix is described in #179
Also, increase BDD test start wait time.
Closes #177
=> chore: Fix master lock race condition, increase test start time

ci/azure-pipelines.yml, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/service.go
Refactored activity handler to support both inbox and outbox handlers. All inbox-specific functions were moved to a new Inbox handler. An Outbox handler will be added in a subsequent commit.
closes #183
=> refactor: Moved inbox-specific functions to Inbox handler

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/store/spi/spi.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/vocab.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/testdata/undo_follow_activity.json
When the inbox receives an 'Undo' activity then the actor is removed from the 'followers' collection. When an 'Undo' activity is posted to the outbox then the object IRI is removed from the 'following' collection.
closes #118
=> feat: Implemented ActivityPub 'Undo' activity to remove follower/following

pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/store/memstore/iterator_test.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go
The ID argument was removed from all activity constructors. IDs may be optionally added using WithID(...).
closes #187
=> refactor: Removed ID from activity constructors

pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go
The inbox handler checks if an activity with the same ID exists in the inbox before processing it. If it already exists then it is ignored.
closes #176
=> feat: Ignore duplicate activities posted to inbox

test/bdd/common_steps.go, test/bdd/features/activitypub.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/testdata/follow_activity.json, test/bdd/go.mod, test/bdd/go.sum
The BDD test randomly failed because duplicate activity IDs were being used in the 'Follow' activity. This commit generates random activity IDs for the Follow and Undo activities.
closes #197
=> fix: Use unique activity IDs in BDD tests

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockoutbox.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
The Outbox.Post signature has changed such that the ID of the activity is returned upon a successful post. When posting an activity to the Outbox then, if the 'id' field hasn't already been set, the Outbox sets the 'id' field of the activity to a unique ID. Also, if the 'actor' field is set then the Outbox validates that it is set to the service IRI otherwise an error is returned. If the 'actor' field is not set then it is set to the service IRI.
closes #182
=> feat: Outbox Post sets the ID and 'actor' of activity

pkg/anchor/handler/credential.go, pkg/anchor/writer/writer.go
There is no need to add activity id and actor - it is now generated by activity pub.
Closes #217
=> chore: Remove creating activity id/actor in handler

cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/client/transport/transport.go, pkg/activitypub/client/transport/transport_test.go, pkg/activitypub/httpsig/signer.go, pkg/activitypub/httpsig/signer_test.go, test/bdd/go.sum
Added a 'go-fed' implementation of HTTP signatures. All ActivityPub requests (GET and POST) are now signed. A future commit will validate the signatures.
closes #175
=> feat: Sign ActivityPub HTTP requests

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/vocab/actortype.go, pkg/activitypub/vocab/actortype_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/internal/aptestutil/aptestutil.go, test/bdd/features/activitypub.feature
Added a REST endpoint to return an actor's public key.
Also refactored the PublicKey type to use an IRI instead of string for the 'id' and 'owner' fields.
closes #223
=> feat: Added REST endpoint to retrieve a public key

pkg/activitypub/client/client.go, pkg/activitypub/client/client_test.go, pkg/activitypub/client/transport/transport.go, pkg/activitypub/client/transport/transport_test.go, pkg/activitypub/httpsig/signer.go, pkg/activitypub/httpsig/signer_test.go, pkg/activitypub/httpsig/verifier.go, pkg/activitypub/httpsig/verifier_test.go, pkg/activitypub/service/mocks/mockactorretriever.go, pkg/internal/aptestutil/aptestutil.go
Implemented an HTTP signature verifier to verify the signature in the HTTP request header. The following steps are performed:
- The public key is retrieved using the key ID in the header (which must be an IRI).
- The owner of the public key is retrieved and the key ID of the owner (actor) must match the key ID in the request header, otherwise the request is rejected.
- The signature in the header is verified using the public key.
closes #238
=> feat: HTTP signature verifier

test/bdd/common_steps.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/httpclient.go
Added steps to get and post signed HTTP requests.
closes #240
=> test: Add support for HTTP signatures in BDD tests

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, test/bdd/features/activitypub.feature
HTTP signatures are validated at the following endpoints:
- /inbox
- /outbox
- /followers
- /following
- /witnesses
- /witnessing
- /likes
- /liked
- /shares
closes #234
=> feat: Verify HTTP signatures in REST endpoints

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/mocks/mockfollowerauth.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go
The ActivityPub 'Follow' handler was refactored so that the code may be reused for the 'InviteWitness' handler.
closes #248
=> refactor: Refactor ActivityPub 'Follow' handler

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/service_test.go, pkg/activitypub/service/spi/spi.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/vocab.go, test/bdd/features/activitypub.feature
Implemented the 'InviteWitness' activity to manage the witness/witnessing collections. For example, Service1 posts the 'InviteWitness' activity to Service2 to ‘ask’ Service2 to be a witness. Service2 either Accepts or Rejects the request. If accepted, Service2 is added to Service1's witnesses collection and Service1 is added to Service2's witnessing collection. Service1 can use ‘Undo’ to remove Service2 from its witnesses collection, which will also remove Service1 from Service2's witnessing collection.
closes #116
=> feat: Implemented 'InviteWitness' activity

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/service_test.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/couchdb-config/config.ini
If a service receives an 'Offer' from an actor that's not in the service's witnessing collection then the activity is rejected.
closes #247
=> fix: Reject Offer activity if actor not in witnessing collection

pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go
Ensure that an activity is sent only once to a URL.
closes #259
=> fix: Deduplicate URLs in outbox

pkg/activitypub/client/transport/transport.go, pkg/activitypub/client/transport/transport_test.go
Content-Type on POST and Accept on GET are set to 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"' for ActivityPub requests.
closes #224
=> fix: Set content type and accept headers on ActivityPub requests

test/bdd/features/did-sidetree.feature
We are not waiting enough for create did and that's why update operation fails.
As a follow-up I will add checks for success for did operations. Currently we have it for resolution only.
Closes #289
=> fix: check for create to be processed before issuing update

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature
Temporarily disable HTTP signature verification in ActivityPub until https://github.com/trustbloc/orb/issues/233 is implemented.
=> chore: Disable HTTP signature verification in ActivityPub

cmd/orb-server/startcmd/start.go, go.mod, pkg/context/cas/ipfs/ipfs.go, pkg/context/cas/ipfs/ipfs_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go
- Added a CAS implementation that can use any Aries provider implementation as a backing store.
- Moved the existing IPFS CAS implementation to a separate folder.
=> feat: CAS based on Aries storage provider

pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/docker-compose.yml
Included:
- disable domain witnessing itself (clarify requirement with @troyronda)
- ignore handling/propagating witness proof if anchor credential has been witnessed already (witness policy = 1 for phase 1)
Closes #323
=> chore: Enable domain self-referencing in allowed anchor origin list

cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.sum, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, pkg/activitypub/service/outbox/outbox.go, test/bdd/did_orb_steps.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/testdata/offer_activity.json, test/bdd/go.sum, test/bdd/restclient/sender.go
Added an endpoint that allows a client to post to it's own service outbox in order to perform admin activities such as add/remove followers and witnesses. A future PR will add access control using HTTP signatures.
closes #117
=> feat: Added REST endpoint to post to outbox

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/builder/builder.go, pkg/anchor/builder/builder_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/fixtures/docker-compose.yml
If domain has local witness log then Orb server should witness anchor credential (instead of just signing it) before sending it to other witness logs for witnessing. This is default behaviour. An option to disable this default behaviour (#332) will be added later.
Also, added maximum witness delay configuration.
Closes #328
=> feat: Witness anchor credential with local witness log

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
Currently we always sign anchor credential with local witness log if available. We should add an option to disable this default behaviour in case that anchor origin (for local witness log) is not referenced in Sidetree batch.
Closes #332
=> chore: Add option to disable signing with local witness log

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/service_test.go, test/bdd/fixtures/docker-compose.yml
The 'to' field of the 'Announce' activity is now set to the actor's '/followers' collection as opposed to setting it to the IRIs of each individual follower. This may result in an 'Announce' activity being posted back to the originator of the 'Create', but there is already handling for duplicate anchor credential at the originator, so this will not be a problem.
closes #347
=> fix: Publish Announce activity to followers

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler.go, test/bdd/features/activitypub.feature
The /activities/{id} REST endpoint returns a single activity by ID.
closes #308
=> feat: Implement /activities REST endpoint

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockproofhandler.go, pkg/activitypub/service/spi/spi.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/proof/proof.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Implement anchor credential witnesses store.
Also:
- add witness to handle proof handler interface
- store batch witnesses plus system witnesses for anchor credential after post offer activity
Closes #350
=> feat: Anchor Credential Witnesses Store

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/authhandler.go, pkg/activitypub/resthandler/authhandler_test.go, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml
Use authorization bearer tokens to authorize ActivityPub requests. If a token is required but not provided then the HTTP signature is verified (if provided).
closes #358
=> feat: Access control with bearer tokens

pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, test/bdd/common_steps.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/features/orb-cli.feature, test/bdd/httpclient.go
When an activity is posted to the /outbox REST endpoint then the ID of the activity is returned in the response.
closes #384
=> feat: Return activity ID from outbox endpoint

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/authhandler.go, pkg/activitypub/resthandler/authhandler_test.go, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, test/bdd/features/activitypub.feature
For server-to-server interactions, access is restricted to witnesses and followers to perform GETs on the following endpoints:
- /followers
- /following
- /outbox
- /inbox
- /witnesses
- /witnessing
- /likes
- /shares
- /activities
Posts to /outbox are restricted to the owner of the outbox.
Posts to /inbox are open to anyone with a valid HTTP signature.
closes #388
=> feat: Restrict server-to-server GETs on certain endpoints

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, test/bdd/features/activitypub.feature
No authentication is required for activities sent to "https://www.w3.org/ns/activitystreams#Public".
closes #392
=> fix: Authorize /activities endpoint

pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Fix add proof in witness proof storage for multiple witnesses.
Closes #401
=> fix: Add proof in witness proof storage

pkg/versions/1_0/operationparser/validators/anchororigin/validator.go, pkg/versions/1_0/operationparser/validators/anchororigin/validator_test.go, pkg/versions/1_0/operationparser/validators/anchortime/validator_test.go
Currently anchor origin is checked against allowed list  if it is provided. However if it is not (nil) it will go through. During early drafts of Orb spec there was an idea about filling in anchor origin if not provided. This requirement got dropped (evolved) later on and anchor origin validator never got updated.
Closes #403
=> fix: Anchor Origin MUST be provided for Create and Recover

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/authhandler.go, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/spi/spi.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, pkg/activitypub/vocab/util.go, pkg/activitypub/vocab/vocab.go, pkg/activitypub/vocab/vocab_test.go, pkg/anchor/writer/writer.go, test/bdd/features/activitypub.feature
Activities in the outbox which are addressed to "https://www.w3.org/ns/activitystreams#Public" are accessible to anyone without authentication.
closes #365
=> feat: No authentication for activities in outbox addressed to public IRI

cmd/orb-cli/common/common_test.go, cmd/orb-cli/createdidcmd/createdid_test.go, cmd/orb-cli/recoverdidcmd/recoverdid_test.go, cmd/orb-cli/updatedidcmd/updatedid_test.go, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/did-keys/create/publickeys.json, test/bdd/fixtures/did-keys/update/publickeys.json, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core: enable key contexts in did documents
Closes #416
=> chore: Enable key contexts in did documents

pkg/anchor/proof/proof.go, pkg/anchor/writer/writer.go, pkg/store/vcstatus/store.go, pkg/store/vcstatus/store_test.go, pkg/store/witness/witness_test.go
Add verifiable credential proof status store.
When verifiable credentials is sent for witnesssing "in-process" status will be added. Upon satisfying proof policy "completed" status will be added.
Closes #378
=> feat: Add verifiable credential status store

cmd/orb-server/startcmd/start.go, pkg/anchor/proof/proof.go, pkg/anchor/writer/writer.go, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bdd/features/did-sidetree.feature
Move updating anchor references from writer to observer. This will allow for having up-to-date did anchor references for following domains too so we will be able to send did updates to following domains.
Add test for updating did document in different domain from where it was created. Of course that domain has to follow original domain.
Closes #441
=> chore: Move updating did anchor references to observer

cmd/orb-server/startcmd/start.go, pkg/activitypub/client/client.go, pkg/activitypub/client/transport/transport.go, pkg/activitypub/client/transport/transport_test.go, pkg/activitypub/httpsig/signer.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/authhandler.go, pkg/activitypub/resthandler/authhandler_test.go, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/service/outbox/httppublisher/httppublisher.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/webcas/webcas.go, pkg/webcas/webcas_internal_test.go, pkg/webcas/webcas_test.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml
If a bearer token is defined for the /cas endpoint then the client must provide a valid token in the header. If a token is not found in the header then the HTTP signature in the header is verified and the actor of the signature is verified to be either a follower or witness.
closes #408
=> feat: Add bearer token authorization for /cas endpoint

pkg/anchor/policy/policy.go, pkg/anchor/policy/policy_test.go
Default behaviour: 100% system and 100% batch
Examples for minimum percent of witnesses required:
MinPercent(50,system) AND MinPercent(100,batch)
MinPercent(50,system) OR MinPercent(50,batch)
Examples for minimum number:
OutOf(1,system) AND OutOf(1,batch)
Closes #445
=> feat: Add witness policy parser/evaluator

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/extendedcasclient/extendedcasclient.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, pkg/webcas/webcas_internal_test.go, pkg/webcas/webcas_test.go, test/bdd/fixtures/.env, test/bdd/fixtures/docker-compose.yml
The CAS resolver is now able to accept either v0 and v1 CIDs and react appropriately (i.e. if v0 received, then v0 used for storage. If v1 received, then v1 used for storage). This means that two Orb servers using different CID versions can now work together.
The BDD tests can now be configured to use either CID format without needing to change the create_activity.json sample data.
Also updated the BDD tests to make one of the Orb domains use v0 while the others use v1 for the sake of proving their compatibility.
closes #344
=> feat: CAS resolver ability to switch between v0 and v1 CIDs dynamically

cmd/orb-driver/go.sum, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/errors/errors.go, pkg/activitypub/errors/errors_test.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/amqp/amqppubsub.go, pkg/activitypub/service/amqp/amqppubsub_test.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/spi/spi.go, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/testdata/undo_follow_activity.json, test/bdd/go.sum
Added support for AMQP-compatible message queue for the publisher/subscriber in ActivityPub. Modified the BDD test to use RabbitMQ for Domain1.
closes #369
=> feat: Support for AMQP message queue in ActivityPub

cmd/orb-server/startcmd/start.go, go.mod, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/policy/config/parser.go, pkg/anchor/policy/config/parser_test.go, pkg/anchor/policy/policy.go, pkg/anchor/policy/policy_test.go
Retrieve witness policy from storage and add cache in front of witness policy storage.
Also, move witness policy parsing to separate package so it can be reused for validating witness policy in upcoming REST handler for updating witness policy. 
Closes #448
=> feat: Configure witness policy: storage and caching

cmd/orb-server/startcmd/start.go, pkg/anchor/policy/policy.go, pkg/anchor/policy/policy_test.go, pkg/anchor/policy/resthandler/configurator.go, pkg/anchor/policy/resthandler/configurator_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/features/did-orb.feature
Add ability to update witness policy. Create new handler that will validate policy and store it into orb config store.
Closes #469
=> feat: Add REST endpoint for updating witness policy

pkg/mocks/protocol.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go
In order to be able to retry anchor processing/did discovery we should ignore already processed operations.
Closes #475
=> chore: Do not store already processed operation

cmd/orb-server/go.mod, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/mocks/mockpubsub.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go, pkg/observer/observer_test.go, pkg/observer/pubsub_test.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/mempubsub/mempubsub.go, pkg/pubsub/mempubsub/mempubsub_test.go, test/bdd/features/did-sidetree.feature
The same message queue instance is now used for ActivityPub (inbox/outbox) and Observer.
closes #473
=> feat: Reuse the same message queue for all services

pkg/activitypub/service/inbox/inbox.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/amqp/pooledsubscriber.go, pkg/pubsub/amqp/pooledsubscriber_test.go, pkg/pubsub/mempubsub/mempubsub.go, pkg/pubsub/spi/spi.go
An AMQP subscriber is handled synchronously and therefore each message in the queue needs to be acknowledged before the next message may be processed. Multiple subscribers are able to handle messages concurrently. The AMQP publisher/subscriber now provides an option for a subscriber pool of a given size allowing messages to be processed concurrently.
closes # 488
=> feat: Subscriber pool for AMQP broker

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/vcpubsub/publisher.go, pkg/anchor/vcpubsub/subscriber.go, pkg/anchor/vcpubsub/vcpubsub_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/observer/pubsub.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Changed the witnessed anchored credential processor to use a publisher/subscriber instead of a Go channel. This allows for a durable message queue to be used.
Also changed the BDD test to use RabbitMQ for all domains.
closes #477
=> feat: Durable message queue for Witnessed Anchor Credentials

pkg/anchor/handler/proof/handler.go, pkg/observer/observer.go, test/bdd/bddtests_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Create new domain that will not follow domain1 (domain3 currently follows indirectly domain1 via domain2) and run did discovery test there.
Closes #505
=> fix: Add new domain for did discovery test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/cas/ipfs/ipfs.go, pkg/observer/observer.go, pkg/resolver/document/resolvehandler.go, pkg/resolver/document/resolvehandler_test.go, test/bdd/fixtures/docker-compose.yml
Even though policy is satisfied some witness proofs may still be empty. Don't add empty witness proof to VC - causes unmarshal error.
Also, adjusted bdd test to have configured did discovery server.
Closes #515
=> fix: Don't add empty proof to VC

cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/resolver/resource/resolver.go, pkg/resolver/resource/resolver_test.go
Also corrected WebFinger retrievals to not use property directly. It now uses that to do a subsequent WebFinger to grab the proper link.
=> feat: Resolve witness via HTTP/HTTPS in addition to IPNS

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/orbclient/client.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/docker-compose.yml
Configure shared domain and add it to did document equivalent id.
Closes #474
=> feat: Configure discovery(shared) domain, add to equivalent id

pkg/activitypub/httpsig/algorithm.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/webcas/webcas.go, pkg/webcas/webcas_test.go, test/bdd/features/did-orb.feature
In the offer activity handler, remove the check that ensures the actor is in the 'witnessing' collection since a witness can be explicitly added to an operation (without being a system witness).
Actor verification for the /cas endpoint is turned off since now the actor is not in the 'witnessing' collection but needs access to the /cas endpoint.
closes #525
=> fix: Don't check if actor in offer activity is being witnessed

cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/httpsig/algorithm.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/mocks/mockpubsub.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/service.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/lifecycle/lifecycle.go, pkg/observer/pubsub.go, pkg/observer/pubsub_test.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, test/bdd/features/did-orb.feature
- Ensure that all services are shut down in proper order:
1. Batch writer
2. Observer
3. ActivityPub service
4. Publisher/subscriber
-  In witness proof handler, publish the VC before setting the status to completed since, if the publisher returns a transient error, this handler would be invoked on another server instance. So, we want the status to remain in-process, otherwise the handler on the other instance would not publish the VC because it would think that is has already been processed.
- Also:
- When storing KMS keys during startup, a delay was added between the time that the key was stored and retrieved in an attempt to handle the race condition where two Orb instances are both storing keys at the same time.
- Fixed a data race in MockPubSub.
closes #532
closes #534
Signed-off-by: …
=> fix: Fix issues related to restart resulting in lost messages/DIDs

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/pubsub/amqp/pooledsubscriber.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Upgraded to the latest sidetree-core-go which defines an explicit 'Nack' for the operation queue when operations are removed. If an error occurs then Nack will be invoked and the removed AMQP messages will also be nacked and the messages will be retried on another subscriber. The message broker may be configured to limit the number of retries.
closes #524
=> fix: Add Nack to operation queue

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/service_test.go
Store the reference using the anchor credential as the object in the reference to the 'Like' activity. Previously the service URI was being used.
closes #549
=> fix: Use the anchor credential as the object in the 'likes' collection

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/vocab/actortype.go, pkg/activitypub/vocab/actortype_test.go, pkg/activitypub/vocab/collection.go, pkg/activitypub/vocab/options.go, pkg/context/opqueue/opqueue.go, test/bdd/features/activitypub.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/httpclient.go
Changed the REST API for shares and likes to:
https://{base-url}/services/orb/shares?id={id}
https://{base-url}/services/orb/likes?id={id}
closes #550
=> fix: REST API for /shares and /likes

.gitignore, test/bdd/bddtests_test.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod
One of the anchor origins in the DID tests is now specified via IPNS. The necessary data is uploaded to IPNS at the beginning of the test.
=> test: IPNS witness resolution in BDD test

pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go, pkg/discovery/endpoint/client/models/endpoint.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go
Move code for retrieving endpoint and resource information from orb client to orb. Same code will be used for discovering latest CID for DID on the server side.
Also, minor linter fix in txn processor.
Closes #563
=> chore: Move endpoint client code to orb

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/anchor/proof/proof.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/webfinger/client/client.go, pkg/webfinger/client/client_test.go, pkg/webfinger/model/model.go, pkg/webfinger/model/model_test.go
Add webfinger client (with caching) with GetLedgerType and HasSupportedLedgerType functions.
Refactor monitoring service to use webfinger client.
Add hasLog flag to witness proof.
Closes #574
=> feat: Add webfinger client; add HasLog flag to witness proof

pkg/anchor/policy/config/parser.go, pkg/anchor/policy/config/parser_test.go, pkg/anchor/policy/policy.go, pkg/anchor/policy/policy_test.go, pkg/anchor/proof/proof.go
Add parsing of LogRequired flag for witness policy.
If witness log is NOT required then all witnesses (with or without log) are counted when evaluating witness policy.
If witness log is required then witnesses without log are not counted when evaluating witness policy.
Closes #511
=> feat: Witness policy for witnesses without VCT log

cmd/orb-server/startcmd/log.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/storeutil/storeutil.go, pkg/anchor/vcpubsub/subscriber.go, pkg/cas/ipfs/ipfs.go, pkg/context/opqueue/opqueue.go, pkg/observer/pubsub.go, pkg/store/operation/store.go, pkg/store/vcstatus/store.go, pkg/store/verifiable/store.go, pkg/store/witness/witness.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, test/bdd/common_steps.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/.env, test/bdd/httpclient.go
- Return transient error in case of DB errors
- Return a transient error when unable to resolve 'followers' or 'witnesses' when posting to the outbox due to a DB error
- Don't attempt to store an empty anchored operation batch to the DB since it results in an 'empty document' error
- Added more logging to help debug problems
Also:
- Use cached store provider for LD document loader to reduce reads from the DB
- Upgrade to CouchDB 3.1.1 (fixes an issue where an error is logged each time the client disconnects)
closes #596
=> fix: Transient error handling

cmd/orb-cli/ipnshostmetauploadcmd/ipnshostmetauploadcmd.go, test/bdd/bddtests_test.go, test/bdd/common_steps.go, test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/go.mod
IPNS upload is now a step at the beginning of the DID tests. This makes it so the IPNS document only gets uploaded for the specific tests that it's needed for. IPNS uploading will also be skipped if the document can already be found at the time of the test.
=> test: Re-enable IPNS tests and skip upload if already there

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/webfinger/client/client.go, pkg/webfinger/client/client_test.go, pkg/webfinger/model/model.go
- WebCAS and WebFinger resolving are now in separate, reusable components.
- Discovery endpoint client can make use of this in the future.
=> feat: Separate WebCAS and WebFinger resolving into reusable components

pkg/anchor/handler/proof/handler.go
Added Info logs and changed existing Debug logs to Info in order to help diagnose a race condition that may occur when multiple proofs for a VC are sent to different server instances in the same domain. The result of this race is that both instances think that additional proofs are required and the VC is never anchored.
=> chore: Additional logs for proof handler

pkg/anchor/writer/writer_test.go, pkg/internal/cacheutil/cacheutil.go, pkg/internal/cacheutil/cacheutil_test.go, pkg/resolver/resource/resolver.go, pkg/resolver/resource/resolver_test.go
Host metadata document should be cached.
Closes #612
=> feat: Add caching to resource resolver

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/observer/observer.go, test/bdd/fixtures/nginx-config/nginx.conf, test/bdd/go.mod, test/bdd/go.sum
Updated to latest sidetree-core-go which reduces the number of INFO and WARNING logs. Also, added an INFO log which indicates the number of DIDs that were processed by the Observer from an anchor.
Also, changed the nginx config so as not to log each HTTP request.
=> chore: Reduce INFO and WARNING logs

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, test/bdd/fixtures/docker-compose.yml
Added a subscriber connection pool that adds a new AMQP connection when the connection subscription limit for the existing connection(s) has been reached. Each connection by default has a 1000 subscription limit, but may be overridden at Orb startup.
closes #634
=> feat: Subscriber connection pool for AMQP client

cmd/orb-server/startcmd/start.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/amqp/pooledsubscriber.go, pkg/pubsub/wmlogger/wmlogger.go, pkg/pubsub/wmlogger/wmlogger_test.go
Currently a goroutine is created for every MQ subscriber channel. This leads to a very large number of goroutines. This commit uses reflect.Select to listen to multiple channels in one goroutine.
Also:
- Reduce the number of logs from Watermill
- Ensure that Prometheus metrics are registered only once in order to fix the startcmd unit tests
closes #641
=> fix: Use select case for pooled subscriber

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/cas/writer/writer.go, pkg/cas/writer/writer_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go
Also refactored metrics provider since the linter was complaining that the function was too long.
And added logging for metrics.
=> chore: Added Prometheus metrics for CAS write and resolve times

pkg/context/opqueue/opqueue.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, test/bdd/fixtures/nginx-config/nginx.conf
Changed the batch cut time metric to measure the time from when the first operation was added to the operation queue to the time that the batch was cut. Also added new metrics to measure the time to ack/nack messages in the operation queue.
closes #644
=> fix: Batch cut time metric

go.mod, pkg/multihash/multihash.go, pkg/multihash/multihash_test.go
These new functions can be used to convert:
- V0 CIDs to multihashes
- V1 CIDs to multihashes
- Multihashes to V1 CIDs
Support for converting multihashes to V0 CIDs to be added in a future commit.
closes #646
=> feat: Added functions for converting between multihashes and CIDs

pkg/observer/observer.go
Equivalent ID for shared domain is missing hash.
Closes #682
=> fix: Equivalent ID for shared domain is missing hash

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/log.go, cmd/orb-server/startcmd/log_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
The LOG_LEVEL startup parameter may now accept either a default log level (as before) or a log spec which contains log levels for individual modules. For example, LOG_LEVEL=metrics=INFO:nodeinfo=WARNING:activitypub_store=INFO:DEBUG.
closes #719
=> feat: Allow for granular log levels for modules on startup

internal/pkg/ldcontext/payload/activity-anchors-v1.json, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchorcredreftype.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab.go, pkg/internal/aptestutil/aptestutil.go
=> chore: Rename 'AnchorCredentialReference' to 'AnchorReference'

pkg/orbclient/client_test.go, pkg/protocolversion/versions/v1_0/client/client.go, pkg/protocolversion/versions/v1_0/client/client_test.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go
Delete operation provider wrappers for client and factory - no longer used.
Closes #671
=> chore: delete operation provider wrappers for client and factory

cmd/orb-server/go.mod, cmd/orb-server/go.sum, test/bdd/common_steps.go, test/bdd/go.mod, test/bdd/go.sum
Also removed some unneeded MySQL code and dependencies that are no longer needed since MySQL support was removed previously.
=> chore: Update MongoDB storage provider version

pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go
Only log the endpoint of the AMQP URL and not the credentials.
closes #762
=> fix: Don't log AMQP credentials

cmd/orb-server/startcmd/start.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, test/bdd/features/did-orb.feature
When handling an 'Announce' activity, a 'Like' is posted to both the actor of the 'Announce' and the creator of the anchor credential.
Also changed the logging of CAS binary content to first base64-encode the content before logging it (since logging binary data sometimes screws up the terminal).
closes #737
=> feat: Also post a 'Like' to the creator of the VC on an 'Announce'

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objecttype_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/vcpubsub/vcpubsub_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/resolver/resolver_test.go, pkg/store/verifiable/store_test.go, pkg/webcas/webcas_test.go, test/bdd/fixtures/testdata/offer_activity.json
Remove references to old anchor crednetial subject model in unit-tests and BDD tests.
Closes #609
=> chore: Remove references to old anchor credential subject model in tests

pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go
Issues:
- remove caching for did anchor origin (we should not have per did caching)
- re-factor endpoint caching (by domain) to use same caching approach as in the rest of Orb
Closes #617
=> chore: Re-visit enpoint client caching

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/config/config.go, pkg/protocolversion/versions/v1_0/factory/factory.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core and add start-up options to add published/unpublished operations to metadata.
Closes #775
=> chore: Add published/unpublished operations to metadata

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/resthandler.go
Return HTTP 400 (bad request) instead of 500 (internal server error) for a REST request that's missing the object ID.
closes #777
=> fix: Return HTTP 400 for missing ID in request

pkg/discovery/endpoint/restapi/anchorinfo.go, pkg/discovery/endpoint/restapi/anchorinfo_test.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/resolver/resource/registry/didanchorinfo/didanchorinfo.go, pkg/resolver/resource/registry/registry.go
When an interim DID is used as a resource ID for a WebFinger query, the response returns the canonical DID if it has been anchored.
closes #780
=> fix: Return the canonical DID in a WebFinger query

pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockanchoreventackhandler.go, pkg/activitypub/service/spi/spi.go, pkg/anchor/handler/acknowlegement/acknowledgement.go, pkg/anchor/handler/acknowlegement/acknowledgement_test.go, pkg/anchor/linkstore/linkstore.go, pkg/anchor/linkstore/linkstore_test.go, pkg/mocks/anchorlinkstore.gen.go, pkg/observer/observer_test.go, test/bdd/common_steps.go, test/bdd/features/did-orb.feature, test/bdd/httpclient.go, test/bdd/state.go
A handler was added to undo a previous Like of an anchor credential. The handler removes all alternate links for the anchor that were previously added by the 'Like' handler.
closes #765
=> feat: Handle 'Undo' Like activity

pkg/cas/resolver/resolver_test.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/webfinger/client/client.go, pkg/webfinger/client/client_test.go, test/bdd/features/did-orb.feature
=> chore: Use alternate relation instead of working-copy for WebFinger CAS query

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/client/client.go, pkg/document/remoteresolver/remoteresolver.go, pkg/document/remoteresolver/remoteresolver_test.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Add an option for resolution from anchor origin. If enabled resolver will request document from anchor origin.
Closes #792
=> feat: Add an option for resolution from anchor origin

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Add missing  published operations from anchor origin to resolution document and metadata by checking local head against anchor origin operations.
Closes #798
=> feat: Add published operations from anchor origin during resolution

cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler_test.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Add expiry to anchor witness store
Closes #852
=> feat: Add expiry to anchor witness store

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/activitypub/service/service.go, pkg/anchor/anchorevent/generator/didorbgenerator/didorbgenerator.go, pkg/anchor/vcpubsub/publisher.go, pkg/context/opqueue/opqueue.go, pkg/observer/pubsub.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/amqp/marshaler.go, pkg/pubsub/amqp/marshaler_test.go, pkg/pubsub/spi/spi.go, test/bdd/features/did-orb.feature, test/bdd/go.sum
Two new queues are added: redelivery and wait.
The 'redelivery' queue is configured as the 'dead-letter-queue' for all queues in Orb. When a message is rejected by a subscriber, it is automatically sent to the 'redelivery' queue. The first time a message is rejected, the redelivery handler immediately redelivers the message to the original destination queue. If the message is rejected again, it is posted to a 'wait' queue and is given an expiration. The 'wait' queue has no subscribers, so the message will sit there until it expires.
The 'redelivery' queue is also configured as the 'dead-letter-queue' for the 'wait' queue, so when the message expires, it is automatically sent back to the 'redelivery' queue and this handler processes the message again. If the message metadata, 'reason', is …
=> feat: MQ redelivery with backoff and maximum attempts

pkg/store/expiry/expiry.go, pkg/store/expiry/expiry_test.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Add handler to expiry service such that it can inspect items to be deleted and take some action (e.g. log them in case they were not expected to be found)
Also, add expiry handler to witness store in order to log unsuccessful anchors (e.g. anchors that failed due to not having enough witnesess)
Closes #854
=> feat: Add handler to expiry service

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.sum, go.mod, go.sum, pkg/activitypub/service/vct/vct.go, pkg/anchor/util/util.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, test/bdd/did_orb_steps.go, test/bdd/go.sum
A single AMQP connection is reused for publishers and subscribers. This reduces the total number of connections, which lowers RabbitMQ resources consumed. Once the channel limit of the connection is reached, a new connection is created for additional subscribers/publishers.
closes #856
=> feat: Reuse AMQP connections for multiple publishers/subscribers

pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/policy/policy_test.go, pkg/anchor/proof/proof.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Refactor batch writer witnesses collection for offer activity:  send individual system witness URLs instead of one preconfigured 'system' witness URL that points to system witnesses collection. Required in order to send only a subset of witnesses (as per policy) in the future.
Closes #861
=> chore: Refactor batch writer witness collection

cmd/orb-cli/acceptlistcmd/acceptlist.go, cmd/orb-cli/acceptlistcmd/acceptlist_test.go, cmd/orb-cli/acceptlistcmd/getcmd.go, cmd/orb-cli/acceptlistcmd/getcmd_test.go, cmd/orb-cli/acceptlistcmd/updatecmd.go, cmd/orb-cli/acceptlistcmd/updatecmd_test.go, cmd/orb-cli/common/common.go, cmd/orb-cli/common/common_test.go, cmd/orb-cli/main.go, pkg/activitypub/service/acceptlist/acceptlist.go, test/bdd/cli_steps.go, test/bdd/common_steps.go, test/bdd/features/orb-cli.feature, test/bdd/features/orb-driver.feature, test/bdd/features/orb-stress.feature
Added an 'acceptlist' command to orb-cli that manages accept lists that are used by the 'Follow' and 'Invite' witness authorization handlers. The command has three sub-commands:
- add - Adds one or more actor URIs to the accept list of a given type (follow or invite-witness)
- remove - Removes one or more actor URIs from the accept list of a given type (follow or invite-witness)
- get - Retrieves all accept lists or an accept list of a specified type (follow or invite-witness)
closes #865
=> feat: Added 'accept list' management command to orb-cli

cmd/orb-server/startcmd/start.go, pkg/anchor/witness/policy/config/parser.go, pkg/anchor/witness/policy/config/parser_test.go, pkg/anchor/witness/policy/policy.go, pkg/anchor/witness/policy/policy_test.go, pkg/anchor/witness/policy/selector/random/selector.go, pkg/anchor/witness/policy/selector/random/selector_test.go, pkg/anchor/witness/proof/proof.go, pkg/anchor/witness/proof/proof_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
Batch writer should select minimum number of witnesses based on policy.
First selector will be random selector.
Closes #866
=> feat: Select minimum number of witnesses based on policy

pkg/anchor/witness/policy/policy.go, pkg/anchor/witness/policy/policy_test.go
Optimize selection of batch and system witnesses by using common witnesses. If there is an intersection between eligible batch witnesses set and eligible system witnesses set then use those common witnesses first during witnesses selection (if witness policy is an AND policy).
Closes #869
=> chore: Optimize selection of system and batch witnesses

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Latest version includes a fix for DocumentDB that ensures that JSON with field names using "." characters store properly without error.
=> chore: Update MongoDB storage provider to latest version

cmd/orb-server/startcmd/start.go, pkg/document/mocks/endpointclient.gen.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, pkg/document/updatehandler/decorator/decorator.go, pkg/document/updatehandler/decorator/decorator_test.go, pkg/document/util/util.go, pkg/document/util/util_test.go, test/bdd/did_orb_steps.go
We should use local knowledge of anchor origin instead of parsing batch files that have already been processed by local server. 
If there was an anchor origin change (anchor origin domain returned different anchor origin for DID) then we will:
- return local result during resolution 
- reject "update", "recover" and "deactivate" operations
Closes #882
=> fix: Use local knowledge for DID anchor domain for resolution from anchor origin

pkg/anchor/witness/policy/policy.go, pkg/anchor/witness/policy/policy_test.go
Add extra logging for policy selection error
Closes #887
=> chore: Add extra logging for policy selection error

cmd/orb-server/startcmd/start.go
=> chore: add InsecureSkipVerify for enableDevMode

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/store/ariesstore/ariesstore_test.go, pkg/internal/testutil/mongodbtestutil/mongodbtestutil.go, pkg/internal/testutil/testutil.go, pkg/nodeinfo/service_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/store/expiry/expiry.go, pkg/store/expiry/expiry_test.go, pkg/store/operation/unpublished/store_test.go, pkg/store/witness/witness_test.go, pkg/taskmgr/taskmgr.go, pkg/taskmgr/taskmgr_test.go
Refactored the expiry service to create a generic task scheduler that may run any task on a single instance in an Orb domain cluster.
Also created a common utility to start a MongoDB container during unit testing (since this code was copied in multiple places). The Docker container is always started on a unique port to prevent the occasional port conflict error.
closes #891
=> refactor: Created generic task scheduling service.

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature
Add negative BDD test for resolution verifier - can be accomplished by mis-configured client.
Closes #898
=> chore: Add negative BDD test for resolution verifier

pkg/activitypub/client/client.go, pkg/activitypub/client/client_test.go, pkg/activitypub/client/util.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/vocab/collection.go, pkg/activitypub/vocab/collection_test.go, pkg/activitypub/vocab/collectionpage.go, pkg/activitypub/vocab/collectionpage_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/typeproperty.go, pkg/internal/aptestutil/aptestutil.go
Added function, GetActivities, to the ActivityPub client so that a server may retrieve activities from another server via a REST endpoint (e.g. https://domain1/services/orb/outbox). The function returns an iterator that iterates over the items in either forward or reverse order.
closes #901
=> feat: Add activities iterator to ActivityPub client

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, test/bdd/fixtures/docker-compose.yml
=> feat: configure http dial and request timeout

pkg/metrics/metrics.go
=> chore: fix lint

cmd/orb-server/startcmd/start.go, pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer.go, test/bdd/fixtures/docker-compose.yml
The anchor event handler now checks all parent anchor events and ensures that they are also processed.
closes #902
=> feat: Ensure parent anchor events are processed

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/anchor/writer/writer_test.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/webfinger/client/client.go, pkg/webfinger/client/client_test.go
Add connection between Orb and VCT server for /vct webfinger query
Closes #890
=> chore: Add webfinger for VCT

pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, test/bdd/features/did-orb.feature
If client attempts to resolve document with equivalent ID (with https hint) from create document store then we will return that ID in resolution response.
Closes #913
=> fix: Create document store should return id with hint (if requested)

pkg/activitypub/service/anchorsynctask/anchorsynctask.go, pkg/activitypub/service/mocks/taskmgr.gen.go, pkg/store/expiry/expiry.go, pkg/taskmgr/taskmgr.go, pkg/taskmgr/taskmgr_test.go
For long running tasks, the timestamp on the permit is periodically updated to tell the other instances in the domain that the instance is still alive.
closes #915
=> feat: Periodically update permit timestamp for long running tasks

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature, test/bdd/go.mod, test/bdd/go.sum
Add BDD test for consecutive updates, second update will be processed in the next batch.
Closes #919
=> chore: Add BDD test for consecutive updates

cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go
Reusing the existing storage provider for the ActivityPub storage reduces the number of connections to MongoDB.
closes #916
=> chore: Reuse existing storage provider for ActivityPub

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/didanchor/memdidanchor/store.go, pkg/didanchor/memdidanchor/store_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/resolver/resource/registry/didanchorinfo/didanchorinfo_test.go, pkg/store/didanchor/store.go, pkg/store/didanchor/store_test.go, pkg/store/operation/store.go, pkg/store/witness/witness.go, test/bdd/go.mod, test/bdd/go.sum
Added an optimization for places that call the store.Batch method using keys that are guaranteed to be new. This optimization speeds up those calls significantly when using MongoDB.
=> feat: MongoDB batch call speed optimization

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/store/operation/unpublished/store.go, pkg/store/operation/unpublished/store_test.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go, test/bdd/features/did-orb.feature, test/bdd/go.mod, test/bdd/go.sum
Included:
- remove current constraint for one operation per suffix in unpublished operation store
- implement multiple operations per suffix in unpublished operation store
- update sidetree-core and BDD tests
Closes #926
=> feat: Add support for multiple operations per suffix in unpublished operation store

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, scripts/generate_test_keys.sh, test/bdd/driver_steps.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>
=> chore: update afgo version

test/bdd/stress_steps.go
- log error when request is taking more than 100ms
=> chore: update stress test

pkg/store/operation/unpublished/store.go
Add index to unpublished operation store
Closes #931
=> fix: Add index to unpublished operation store

pkg/document/resolvehandler/resolvehandler.go, pkg/metrics/metrics.go, pkg/mocks/metricsprovider.go
Add metrics for document resolution:
- resolving document locally
- getting anchor origin endpoint info
- resolving document from anchor origin
- deleting document from create document store
- resolving document from create document store
- verifying CID for document resolution
- request discovery
Closes #938
=> chore: Add metrics for document resolution

cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/client/client.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/service.go, test/bdd/fixtures/docker-compose.yml
Added startup parameters for the actor/public-key cache, as well as the actor IRI cache in the Outbox.
closes #940
=> chore: Add startup parameters for ActivityPub cache sizes

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, test/bdd/common_steps.go, test/bdd/features/did-orb.feature
The ActivityPub /liked collection now returns a collection of hashlinks of anchor events that were 'liked' by the local service as opposed to a collection of activities.
closes #933
=> fix: Invalid objects for /liked REST endpoint

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Updated to the latest sidetree-core-go which provides a performance optimization such that adding new operations doesn't ever have to wait for a batch to be cut.
=> fix: Don't wait for batch cut when adding new operation

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/anchorsynctask/anchorsynctask_test.go, pkg/activitypub/service/mocks/taskmgr.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, pkg/store/expiry/expiry.go, pkg/taskmgr/taskmgr.go, test/bdd/fixtures/docker-compose.yml
An operation processed from the message queue is now stored in the database and immediately acknowledged (as opposed to waiting for the batch to be cut before acknowledging). This strategy reduces the number of subscribers required to process a batch and therefore reduces the resources required by an AMQP provider. Background Go routines monitor the operation queue tasks and operations such that queue tasks from one server instance that are stale are re-posted by another server instance, and really old operations are deleted from the database. The default value of the MQ subscriber queue is now set to 5. So, instead of 5000 MQ subscribers that were previously required to process a batch of 5000, the default is now 5 (although it still works if this value is set to 1).
closes #944 …
=> feat: Use the DB to ensure reliability for the operation queue instead of the AMQP provider

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: add http metrics for create and resolve

pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, pkg/orbclient/resolutionverifier/resolutionverifier.go, pkg/orbclient/resolutionverifier/resolutionverifier_test.go
Canonical ID and anchor origin are now part of checks for equality of resolutions results for both server and client.
Closes #951
=> chore: Add canonical ID and anchor origin to resolution equality check

test/bdd/stress_steps.go
=> chore: fix stress test

test/bdd/features/did-sidetree.feature
Test for multiple operations for same suffix being split in multiple batches is time sensitive to be detected so remove this variable from BDD test. We are still testing for correct behaviour.
Closes #958
=> chore: Fix secondKey NOT found failure in BDD test

pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchoreventtype.go, pkg/activitypub/vocab/anchoreventtype_test.go, pkg/activitypub/vocab/options.go, pkg/anchor/anchorevent/anchorevent.go, pkg/anchor/anchorevent/generator/didorbgenerator/didorbgenerator_test.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/util/util_test.go, pkg/anchor/vcpubsub/vcpubsub_test.go, pkg/anchor/writer/writer.go, pkg/internal/aptestutil/aptestutil.go, pkg/store/anchorevent/store_test.go
=> chore: Rename 'anchors' to index

pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, pkg/errors/errors.go, pkg/errors/errors_test.go, test/bdd/features/activitypub.feature
The "Undo" activity is now validated against the original activity that is being undone. If it does not match then HTTP 400 (bad request) is the response.
closes #874
=> fix: Reject invalid "Undo" request

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/referencehandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/ariesstore/ariesstore_test.go, test/bdd/go.mod, test/bdd/go.sum
Create a new, "activitypub-ref" database that contains all of the references that were previously in 11 separate databases.
closes #872
closes #873
=> chore: Amalgamate ActivityPub reference databases

pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go
After an operation has been retried for a number of times greater than the max retry count, it will be abandoned in order to prevent a situation where retries are infinite.
closes #971
=> fix: Added max retries to operation

pkg/document/util/util.go, pkg/orbclient/resolutionverifier/resolutionverifier.go, pkg/orbclient/resolutionverifier/resolutionverifier_test.go
=> fix: remove unpublishedLabel from resolution verifier

test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Decrease time scheduler time for domain4 so witness re-selection test can execute faster.
Closes #991
=> chore: Adjust task scheduler time for domain4

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/wmlogger/wmlogger.go, pkg/pubsub/wmlogger/wmlogger_test.go, test/bdd/fixtures/docker-compose.yml
Use the latest watermill-amqp client library which implements a Publisher channel pool. The channel pool improves performance in high volume systems by not incurring the overhead of opening and closing channels, and the pool also acts as a throttle to prevent the AMQP server from overloading.
Also, use separate AMQP connections for publishers and subscribers since this is recommended for RabbitMQ (https://www.cloudamqp.com/blog/part1-rabbitmq-best-practice.html#separate-connections-for-publisher-and-consumer).
closes #943
closes #985
=> feat: Use an AMQP channel pool for the publisher

pkg/anchor/writer/writer.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
The metric, anchor_write_sign_local_store_seconds, was renamed to anchor_write_store_seconds since it has nothing to do with signing.
=> fix: Rename anchor_write_sign_local_store_seconds metric

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/amqp/marshaler.go, pkg/pubsub/amqp/marshaler_test.go, test/bdd/go.sum
=> chore: Use latest watermill-amqp library

pkg/anchor/witness/policy/config/parser.go, pkg/anchor/witness/policy/config/parser_test.go
Currently for minimum number of witnesses in witness policy rule OutOf() we only check for integer for first parameter. It should be 0 or positive integer since it denotes minimum number of witnesses required to satisfy policy.
Percent rule MinPercent() is already enforcing integer that is between 0 and 100 which is correct for percent.
Closes #1025
=> chore: Add 0 or positive check for minimum number of witnesses required.

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/witness/policy/policy.go, test/bdd/fixtures/docker-compose.yml
Add configuration for witness policy expiry cache. Currently it is defaulted to 30s.
Closes #1028
=> chore: Add configuration for witness policy expiry cache

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/document/updatehandler/decorator/decorator.go, pkg/document/updatehandler/decorator/decorator_test.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/go.mod, test/bdd/go.sum
Block DID operations that are issued after successful deactivate operation at REST API.
Updated sidetree-core, added BDD test for issuing operation after deactivate.
Closes #1032
=> chore: Do not accept DID operations after successful deactivate operation

cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/features/did-orb.feature, test/bdd/features/onboard-recovery.feature, test/bdd/fixtures/docker-compose.yml
For a standalone domain, where no witnesses are configured and the witness policy states that I don't need witnesses, the anchor event is processed immediately using only the proof of the local domain.
closes #1064
=> fix: Process anchor event immediately if witness policy does not require witnesses

test/bdd/bddtests_test.go, test/bdd/features/orb-stress.feature, test/bdd/stress_steps.go
=> fix: make auth token configurable

cmd/orb-cli/createdidcmd/createdid.go, cmd/orb-cli/createdidcmd/createdid_test.go, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/resolvedidcmd/resolvedid.go, cmd/orb-cli/updatedidcmd/updatedid.go
=> fix: http client in cli

test/bdd/did_orb_steps.go, test/bdd/features/backup-restore.feature, test/bdd/state.go
Two BDD steps are added:
- create_dids_to_file: Creates a number of DIDs and stores the DIDs to a file.
- verify_created_dids_from_file: Verifies the DIDs from the given file. The file may be on the local file system or on an HTTP server.
closes #1063
=> test: Add BDD steps to be used by AWS backup and restore testing

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Should fix the error: invalid number of parts[3] for Orb identifier.
=> fix: DID resolver sometimes does not return DID with four parts

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Fixes a race condition in DID resolve.
=> fix: Update to latest sidetree-core-go

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/anchorsynctask/anchorsynctask.go, pkg/activitypub/service/anchorsynctask/anchorsynctask_test.go, test/bdd/fixtures/docker-compose.yml
A minimum activity age parameter is added to the anchor sync task such that the activity needs to be older than this value before it is processed (according to the "published" time of the activity).
For example, the anchor sync task should not process activities that are younger than 1 minute. The minimum age is configurable via the ANCHOR_EVENT_MIN_ACTIVITY_AGE startup parameter (default 1m).
closes #1085
=> fix: Add minimum activity age param to anchor sync task

test/bdd/did_orb_steps.go, test/bdd/utils.go
The BDD step verify_created_dids_from_file now supports ZIP files as well as plain text files.
=> test: Support for reading compressed DID file

.gitignore, test/bdd/did_orb_steps.go, test/bdd/features/create-dids-to-file.feature
The number of DIDs to create and the concurrency are now configurable using the environment variables ORB_BACKUP_NUM_DIDS and ORB_BACKUP_CONCURRENCY.
closes #1093
=> test: Add env vars to BDD step create_dids_to_file

Makefile, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockoutbox.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/spi/spi.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/witness/policy/inspector/inspector.go, pkg/anchor/witness/policy/inspector/inspector_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/observer/observer.go
When announcing a Create activity to followers, the actor in the Create activity is excluded
since this results in the actor processing the same anchor twice.
closes #1095
=> fix: Don't announce to the actor in the Create activity

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/anchorsynctask/activitysynctask.go, pkg/activitypub/service/anchorsynctask/activitysynctask_test.go, pkg/activitypub/service/spi/spi.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go, test/bdd/go.mod, test/bdd/go.sum
If the transaction processor determines that all of the operations in the batch are already in local storage then a check is made to see if the anchor is also store. If so, the anchor will not be processed again. (This is most likely due do multiple Announce activities announcing the same anchor event.)
closes #1104
=> feat: Check if anchor exists if 0 operations processed

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/opqueue/opqueue.go, pkg/observer/observer.go, pkg/observer/pubsub.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/pooledsubscriber.go, pkg/pubsub/spi/spi.go
=> chore: Add startup parameters for AMQP redelivery

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchoreventtype.go, pkg/activitypub/vocab/anchoreventtype_test.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/util.go, pkg/activitypub/vocab/util_test.go, pkg/activitypub/vocab/vocab.go, pkg/anchor/anchorevent/anchorevent.go, pkg/anchor/anchorevent/anchorevent_test.go, pkg/anchor/anchorevent/generator/didorbgenerator/didorbgenerator_test.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/util/util_test.go, pkg/anchor/witness/policy/inspector/inspector_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/internal/aptestutil/aptestutil.go, pkg/observer/observer_test.go, pkg/orbclient/aoprovider/anchororiginprovider_test.go, test/bdd/common_steps.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/testdata/create_activity.json, test/bdd/fixtures/testdata/offer_activity.json
The AnchorEvent model is changed to use the ActivityStreams "content" and "mediaType" fields instead of the "contentObject" field. The content field contains a content object which is encoded according to the "mediaType" field. Two media types are currently supported: "application/json" and "application/gzip".
- The application/json media type escapes the JSON fields and embeds them in the "content" field.
- The application/gzip media type compresses the JSON content and base64-encodes the compressed data
closes #997
=> feat: Change AnchorEvent attachments to use encoded content

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/opqueue/opqueue.go, test/bdd/features/onboard-recovery.feature, test/bdd/fixtures/docker-compose.yml
=> chore: Added startup parameters for operation queue

test/bdd/did_orb_steps.go, test/bdd/features/create-dids-to-file.feature, test/bdd/httpclient.go
- Modify the step, create_dids_to_file, so that the DIDs are not verified. This allows other steps to immediatley run withouthout waiting for the DIDs to be anchored.
- Modify step, verify_created_dids_from_file, to add the env parameter ORB_BACKUP_VERIFY_ATTEMPTS to specifiy the maximum number of attempts to verify that a DID has been anchored.
closes #1122
=> test: Modify create-dids-to-file BDD test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/protocol/client/client.go, pkg/context/protocol/client/client_test.go, pkg/context/protocol/provider/provider_test.go, test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose-testver.yml
Add ability to set current protocol version (used for accepting operations and rendering did document). This will allow us to deploy new code and keep processing requests as per previous version. Also, observer will be able to process anchors with advanced protocol version.
Close #1126
=> feat: Configure current protocol in Protocol Client

cmd/orb-server/startcmd/params.go, pkg/anchor/witness/policy/inspector/inspector.go, pkg/anchor/witness/policy/inspector/inspector_test.go, pkg/context/opqueue/opqueue.go, pkg/errors/errors.go, pkg/store/anchoreventstatus/store.go, pkg/store/anchoreventstatus/store_test.go
Currently an error is logged when no additional witnesses are found. This is changed to Info since it's not critical.
Also, renamed the operation queue monitor task and changed the default anchor status grace period to 30s from 1m.
=> chore: Change log level for 'no witnesses' error

test/bdd/bddtests_test.go, test/bdd/did_orb_steps.go, test/bdd/workerpool.go
The log-level may be specified by environment variable LOG_LEVEL. The accepted values are:
- debug
- info
- warning
- error
If the environment variable is not set then info is used by default.
closes #1138
=> test: Add log-level option to BDD test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go, test/bdd/fixtures/docker-compose.yml
Currently witness store expiry period is calculated as max witness delay + hard-coded delta. Modify this functionality to use configured parameter.
Closes # 1132
=> feat: Configure Witness Store Expiry Period

cmd/orb-server/startcmd/start.go, pkg/anchor/witness/policy/resthandler/configurator.go, pkg/anchor/witness/policy/resthandler/retriever.go, pkg/anchor/witness/policy/resthandler/retriever_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
=> feat: REST endpoint to retrieve witness policy

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/document/mocks/dochandler.gen.go, pkg/document/mocks/endpointclient.gen.go, pkg/document/mocks/operationprocessor.gen.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/updatehandler/decorator/decorator.go, pkg/orbclient/resolutionverifier/resolutionverifier.go, pkg/resolver/resource/registry/didanchorinfo/didanchorinfo.go, pkg/resolver/resource/registry/didanchorinfo/mocks/operationprocessor.gen.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core, add BDD test for retrieving documents by versionId.
Closes #1148
=> chore: Add BDD test for retrieving documents by versionID

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/common_steps.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core and add BDD test for resolve DID with versionTime parameter
Closes #1151
=> chore: BDD test for resolve DID with versionId

pkg/activitypub/vocab/collection.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objecttype.go, pkg/anchor/anchorevent/vocab/datauri.go, pkg/anchor/anchorevent/vocab/datauri_test.go, pkg/anchor/anchorevent/vocab/linkset.go, pkg/anchor/anchorevent/vocab/linkset_test.go, pkg/internal/testutil/testutil.go
Implement a subset of the Linkset vocabulary (https://www.ietf.org/archive/id/draft-ietf-httpapi-linkset-08.html) which will be used as a replacement for AnchorEvent.
closes #1157
=> feat: Implement subset of Linkset vocabulary

cmd/orb-server/startcmd/start.go, go.mod, pkg/activitypub/service/vct/monitor/monitor.go, pkg/activitypub/service/vct/monitor/monitor_test.go
The fist version will:
- query STH head
- verify STH signature
- retrieve STH consistency between two STH heads
- verify STH consistency between two STH heads
Closes #1175
=> feat: Add VCT consistency monitor

pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/ariesstore/ariesstore_test.go, pkg/anchor/linkstore/linkstore.go, pkg/store/anchorstatus/store.go, pkg/store/cas/cas.go
Modified some database names for consistency and to reflect what they store.
=> chore: Change DB names to be more meaningful

pkg/store/logmonitor/store.go, pkg/store/logmonitor/store_test.go
Store will be used for tracking logs that will be monitored by Orb server. It will be used by log monitoring service (get active logs, update STH for log) and orb-cli (activate, deactivate, delete)
Store operations:
- activate log
- deactivate log
- update log
- delete log
- get active logs
Closes #1194
=> feat: Add log monitor store

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/vct/monitor/monitor.go, pkg/activitypub/service/vct/monitor/monitor_test.go, pkg/activitypub/service/vct/proofmonitoring/monitoring.go, pkg/activitypub/service/vct/proofmonitoring/monitoring_test.go, pkg/store/logmonitor/store.go, test/bdd/go.sum
When Orb domain starts monitoring VCT log with previous records(e.g. during on-boarding):
- fetch all the entries in the tree corresponding to the STH
- confirm that the tree made from the fetched entries produces the same hash as that in the STH
Closes #1178
=> feat: Verify STH from log entries

pkg/context/opqueue/opqueue_test.go, pkg/internal/testutil/mongodbtestutil/mongodbtestutil.go, pkg/internal/testutil/rabbitmqtestutil/rabbitmqtestutil.go, pkg/pubsub/amqp/amqppubsub_test.go
For some reason, when running our unit tests the MongoDB and RabbitMQ container port allocations may not be released (or may take some time to be released), resulting in errors for later tests. The code that starts up the MongoDB Docker image tries different ports until it finds a free one, but the existing attempt limit of 3 seems to be insufficient now, so I bumped it up to 10. I also added the same type of port-retry behaviour for the tests that start up RabbitMQ Docker containers, as they suffer from the same problem.
=> fix: Unit test MongoDB and RabbitMQ port allocation errors

pkg/activitypub/client/client.go, pkg/activitypub/httpsig/verifier.go, pkg/activitypub/httpsig/verifier_test.go, pkg/anchor/util/util.go, test/bdd/did_orb_steps.go, test/bdd/features/onboard-recovery.feature
Modified the existing onboarding-and-recovery BDD test to take down an Orb instance while DIDs are being created, in order to prove that no DIDs are lost in a busy system when a domain instance goes down.
Also added a fix to the HTTP signature verifier to propagate a transient HTTP error to the caller so that a transient error may be retried.
closes #1225
=> test: Updated onboarding and recover BDD test to handle instance failure

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/features/orb-driver.feature, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core, add did lifecycle BDD test
Closes #1229
=> chore: Add created and updated to did doc metadata

pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/anchor/handler/credential/handler.go, pkg/observer/observer.go
The ActivityPub Outbox now uses the AMQP Pub/Sub subsystem for retrying an unreachable domain. When a destination URL is unreachable, the AMQP message is NACK'ed and the operation is retried with a backoff and maximum number of attempts so as not to retry forever.
closes #1242
=> fix: Outbox retries forever if target domain is down

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/vct/logmonitoring/monitor.go, pkg/activitypub/service/vct/logmonitoring/monitor_test.go, pkg/activitypub/service/vct/logmonitoring/verifier/verifier.go, pkg/activitypub/service/vct/logmonitoring/verifier/verifier_test.go, pkg/store/logentry/store.go, pkg/store/logentry/store_test.go, test/bdd/fixtures/docker-compose.yml
Store log entries.
Closes #1240
=> feat: Store log entries

pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go
=> refactor: Rename outbox message types

test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose-testver.yml
Add BDD test for verifying log's Merkle tree STH from get-entries. This happens when domain starts to follow another domain with log size > 0.
Closes #1197
=> chore: Add BDD test for verifying new log with tree size > 0

pkg/store/logentry/store.go, pkg/store/logentry/store_test.go
Implement retrieving log entries to log-entries store. Initially it is only used to test stored log entries.
Closes #1256
=> feat: Add retrieving log entries

cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go, pkg/store/anchorstatus/store.go, pkg/store/anchorstatus/store_test.go, pkg/store/publickey/publickeystore.go, pkg/store/publickey/publickeystore_test.go, test/bdd/did_orb_steps.go, test/bdd/utils.go
Implemented a public key storage and cache for the Observer. When verifying a witness proof, the Observer will load the public key of the signer from the cache/database. If it doesn't exist in the DB then the public key is retrieved using the public key fetcher.
Also enhanced the BDD test so that, when creating DIDs on multiple targets, the target will be greylisted if it is down and the create will be performed on another target.
closes #1261
=> feat: Public key store/cache for Observer

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go
Remove unused VCT discovery domains parameter
Closes #1265
=> chore: Remove unused vct discovery domains parameter

cmd/orb-server/startcmd/start.go, pkg/vct/resthandler/configurator.go, pkg/vct/resthandler/configurator_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Add REST endpoint to configure/store VCT URL
Closes #1273
=> feat: Add REST endpoint to configure/store VCT URL

pkg/config/client/client.go, pkg/config/client/client_test.go
It will be used by components that use VCT URL as parameter.
Closes #1277
=> feat: Add client for caching config store (config-db parameters)

cmd/orb-server/startcmd/start.go, pkg/vct/resthandler/retriever.go, pkg/vct/resthandler/retriever_test.go, test/bdd/features/did-orb.feature
Add REST endpoint to retrieve log URL
Closes #1283
=> feat: Add REST endpoint to retrieve log URL

cmd/orb-server/startcmd/start.go, pkg/vct/logmonitoring/resthandler/update.go, pkg/vct/logmonitoring/resthandler/update_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Add REST endpoint to deactivate log URL (when it is no longer required to monitor e.g. old log). Also, add endpoint to activate log.
Closes #1276
=> feat: Add REST endpoint to deactivate/activate log URL

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/store/expiry/expiry.go, test/bdd/did_orb_steps.go, test/bdd/docker_steps.go, test/bdd/features/onboard-recovery.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum, test/bdd/httpclient.go
When an AMQP server is restarted, the Orb pub-sub client receives a success response when publishing a message even though the message may not have been persisted by the AMQP server (because the server has died) and therefore the message is lost. This commit uses the latest version of watermill-amqp which adds a delivery confirmation feature. A failed delivery confirmation results in the message being retried (according to the pub-sub redelivery mechanism).
A new startup parameter was added to enable/disable delivery confirmations. Delivery confirmations are enabled by default.
(Note that the delivery confirmation pull request (https://github.com/ThreeDotsLabs/watermill-amqp/pull/15) has not yet been merged, so this commit points to the TrustBloc fork of watermill-amqp. Once the PR is …
=> feat: Enable AMQP publisher delivery confirmation

pkg/anchor/util/util.go, pkg/store/publickey/publickeystore.go, pkg/store/publickey/publickeystore_test.go, test/bdd/did_orb_steps.go, test/bdd/features/onboard-recovery.feature
Added a BDD test for restarting a database while Orb instances are up.
Also, added a fix to ensure a transient error is returned after getting a VC parse error due to the DB being down.
closes #1295
=> test: BDD test for database restart

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, test/bdd/features/activitypub.feature, test/bdd/features/create-dids-to-file.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/features/onboard-recovery.feature, test/bdd/features/orb-cli.feature, test/bdd/features/orb-driver.feature, test/bdd/features/orb-stress.feature, test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose.yml
We should be able to spin orb without any configuration so add VCT enabled/disabled flag.
Closes #1287
=> feat: Add environment variable for no VCT version

cmd/orb-cli/main.go, cmd/orb-cli/policycmd/getcmd.go, cmd/orb-cli/policycmd/getcmd_test.go, cmd/orb-cli/policycmd/policy.go, cmd/orb-cli/policycmd/policy_test.go, cmd/orb-cli/policycmd/updatecmd.go, cmd/orb-cli/policycmd/updatecmd_test.go, test/bdd/cli_steps.go, test/bdd/common_steps.go, test/bdd/features/orb-cli.feature
Added commands to the Orb CLI to update and retrieve a witness policy for an Orb domain.
closes #1286
=> feat: Add witness policy management to Orb CLI

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.sum
The latest watermill-amqp library fixes a deadlock that occurs in the subscriber after a RabbitMQ restart and adds a publisher delivery confirmation option. This PR replaces the forked version of the watermill-amqp library.
closes #1270
=> chore: Update to latest version of watermill-amqp

cmd/orb-cli/logmonitorcmd/getcmd.go, cmd/orb-cli/logmonitorcmd/getcmd_test.go, cmd/orb-cli/logmonitorcmd/logmonitor.go, cmd/orb-cli/logmonitorcmd/logmonitor_test.go, cmd/orb-cli/logmonitorcmd/updatecmd.go, cmd/orb-cli/logmonitorcmd/updatecmd_test.go, cmd/orb-cli/main.go, test/bdd/features/orb-cli.feature
Add log monitor get, activate, deactivate cmd to CLI
Closes #1299
=> feat: Add log monitor get, activate, deactivate cmd to CLI

.github/workflows/build.yml, cmd/orb-cli/common/common.go, cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-cli/main.go, cmd/orb-cli/policycmd/policy.go, cmd/orb-cli/policycmd/updatecmd.go, cmd/orb-cli/vctcmd/vct.go, cmd/orb-cli/vctcmd/vct_test.go, cmd/orb-cli/vctcmd/verifycmd.go, cmd/orb-cli/vctcmd/verifycmd_test.go, test/bdd/bddtests_test.go, test/bdd/cli_steps.go, test/bdd/common_steps.go, test/bdd/features/orb-cli.feature, test/bdd/go.mod, test/bdd/go.sum
The orb-cli vct verify command verifies that the proofs of an anchor linkset are actually included in the VCT log.
closes #1302
=> feat: Added vct verify command to orb-cli

pkg/httpserver/server.go
=> fix: health check status

samples/docker/docker-compose-dev-vct.yml, samples/docker/docker-compose-dev.yml, samples/tutorial/docker-compose-cli.yml
Depending on the routes given out by workplace VPNs somebody may have
trouble running the tutorial when on a workplace VPN.
$ docker-compose -f docker-compose-cli.yml -f ../docker/docker-compose-dev.yml up
Creating network "tutorial_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
By specifying the network used for all containers we can run all the
"up" parts of the docker-compose step without encountering this error.
=> chore: specify a subnet for workplace VPN compatibility

pkg/store/logentry/store.go, pkg/store/logentry/store_test.go
Log entry store should be able to mark 'failed' entries so they can be examined later on.
Closes #1321
=> feat: Add status to log entry store

cmd/orb-server/startcmd/start.go, pkg/vct/logmonitoring/monitor.go, pkg/vct/logmonitoring/monitor_test.go, test/bdd/features/onboard-recovery.feature, test/bdd/fixtures/docker-compose.yml
When Orb server detects that VCT log tree size is behind recorded Orb tree size (which can happen in case that VCT DB is restored from back-up) currently it generates and logs an error.
Instead:
- log that anomaly was detected for stored and log tree size
- flag missing log entries in entry store as failed in log entry DB so they can be identified later on
- adjust current Orb tree size (STH) so that VCT log consistency check can proceed as usual.
Closes #1318
=> feat: Orb node should detect unexpected VCT log changes

cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/linkstore/linkstore.go, pkg/anchor/witness/policy/inspector/inspector_test.go, pkg/anchor/writer/writer_test.go, pkg/store/anchorlink/store.go, pkg/store/anchorlink/store_test.go, pkg/store/anchorstatus/store.go, pkg/store/anchorstatus/store_test.go, pkg/store/publickey/publickeystore.go
The following stores were converted to use the optimized storage interface:
- anchor-link
- anchor-status
- anchor-ref
- verifiable
- public-key
closes #1325
closes #1330
=> feat: Optimized stores for anchor/VC

pkg/store/logentry/store.go, pkg/store/logentry/store_test.go, pkg/store/logmonitor/store.go, pkg/store/logmonitor/store_test.go, pkg/vct/proofmonitoring/monitoring.go, pkg/vct/proofmonitoring/monitoring_test.go, test/bdd/features/did-orb.feature, test/bdd/features/orb-cli.feature
The DB, monitoring, was renamed to proof-monitor and the following stores were converted to use the optimized storage interface:
- log-monitor
- proof-monitor
- log-entry
closes #1326
=> feat: Optimized stores for VCT monitoring

cmd/orb-cli/go.mod, cmd/orb-driver/go.mod, pkg/anchor/witness/proof/proof.go, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/store/operation/store.go, pkg/store/operation/store_test.go, pkg/store/operation/unpublished/store.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Renamed DB, op-queue, to, operation-queue, and the following stores were converted to use the optimized storage interface:
- operation
- operation-queue
- unpublished-operation
- witness
closes #1327
closes #1328
=> feat: Optimized stores for operation & witness

.gitignore, Makefile, cmd/orb-server/main.go, pkg/activitypub/resthandler/openapi.go, pkg/anchor/anchorlinkset/vcresthandler/openapi.go, pkg/anchor/witness/policy/resthandler/openapi.go, pkg/discovery/endpoint/restapi/openapi.go, pkg/discovery/endpoint/restapi/operations.go, pkg/metrics/openapi.go, pkg/nodeinfo/openapi.go, pkg/vct/resthandler/openapi.go, pkg/webcas/openapi.go
Added swagger docs for:
- /acceptlist
- /services/orb
- /services/orb/activities
- /services/orb/followers
- /services/orb/following
- /services/orb/inbox
- /services/orb/keys
- /services/orb/liked
- /services/orb/outbox
- /services/orb/shares
- /services/orb/witnesses
- /services/orb/witnessing
- /cas
- /log
- /metrics
- /nodeinfo
- /policy
- /vc
Also updated the Makefile 'checks' target to also validate the open-api-spec.
closes #575
closes #1351
=> docs: Swagger docs

go.sum, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/ariesstore/ariesstore_test.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/store/spi/spi.go
The actor store is not used.
closes #1356
=> chore: Remove ActivityPub actor store

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service_test.go, pkg/httpserver/server.go, pkg/httpserver/server_test.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/mempubsub/mempubsub.go, test/bdd/common_steps.go, test/bdd/features/onboard-recovery.feature
Reuse existing connection when testing AMQP connectivity.
=> fix: AMQP health check

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/protocol.go, pkg/protocolversion/factoryregistry/factoryregistry.go, pkg/protocolversion/versions/test/v_test/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: Add CAS write size metric

pkg/store/mocks/mongodbstore.gen.go, pkg/store/store.go, pkg/store/store_test.go, pkg/store/wrapper/store.go, pkg/store/wrapper/store_test.go
Added an optimization that will improve performance with batch calls made to the MongoDB wrapper using keys that are known ahead of time to not already exist in the database. This optimization used to be in Orb but was lost with some recent database changes.
=> feat: MongoDB wrapper batch method optimization

pkg/pubsub/amqp/amqppubsub.go
Configure the wait queue with a small publisher pool so as not to waste resources.
closes #1370
=> fix: Use dedicated publisher pool for wait queue

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/amqp/publisherpool.go, pkg/pubsub/amqp/publisherpool_test.go, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml
If the pool size exceeds the maximum number of channels per connection then multiple publisher pools are created, each pool having a dedicated connection. The pools are distributed evenly.
Also renamed startup parameter/environment variable from mq-max-connection-subscriptions/MQ_MAX_CONNECTION_SUBSCRIPTIONS to mq-max-connection-channels/MQ_MAX_CONNECTION_CHANNELS since it is used for publisher as well as subscriber pools.
closes #1372
=> feat: Use multiple publisher pools if pool size is to large

cmd/orb-cli/allowedoriginscmd/allowedorigins.go, cmd/orb-cli/allowedoriginscmd/allowedorigins_test.go, cmd/orb-cli/allowedoriginscmd/getcmd.go, cmd/orb-cli/allowedoriginscmd/getcmd_test.go, cmd/orb-cli/allowedoriginscmd/updatecmd.go, cmd/orb-cli/allowedoriginscmd/updatecmd_test.go, cmd/orb-cli/main.go, test/bdd/features/orb-cli.feature
=> feat: Added allowedorigins command to Orb CLI

test/bdd/features/create-dids-to-file.feature
Move the setup portion to scenario, create_and_verify_dids_from_file, since this is the only scenario that runs in the CI.
closes #1383
=> fix: Create_dids_to_file BDD test scenario

test/bdd/did_orb_steps.go, test/bdd/workerpool.go
=> test: Add progress logs to create_dids_to_file scenario

pkg/store/anchorstatus/store.go
Modified the anchor status task to only check anchors that are 'in-process'.
closes #1387
=> fix: Anchor status task checks only in-process status

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/mocks/pubsub.gen.go, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/pubsub/amqp/amqppubsub.go, pkg/pubsub/amqp/amqppubsub_test.go, pkg/pubsub/mempubsub/mempubsub.go, pkg/pubsub/spi/spi.go
When an operation in the queue fails to process then the retry adds a delay so that the message broker doesn't retry the operation immediately.
closes #1137
=> feat: Add backoff to operation queue retries

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, pkg/context/opqueue/opqueue.go
There is no need to have a separate set of parameters for the operation queue that dictate retry behavior since the parameters are already defined for the pub-sub subsystem.
=> chore: Reuse the MQ parameters for operation queue

pkg/protocolversion/versions/v1_0/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol_test.go
Add "P-384" to protocol parameters
Closes #1350
=> chore: Add P-384 to protocol params

pkg/config/client/client.go, test/bdd/features/did-orb.feature, test/bdd/features/orb-cli.feature
Add new tests that will:
1. create did, rotate log, update did and check for updated did in rotated log
2. create, update, recover and deactivate did after log rotation and check existence in rotated log
Closes #1391
=> chore: Add rotate log with DID operations CLI test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, test/bdd/fixtures/docker-compose.yml
… timestamps
Check VC timestamp against witness timestamp.
Closes #1336
=> Properly dealing with late publishing based on witness timestamps

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/outbox/outbox.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/witness/policy/inspector/inspector.go, pkg/anchor/witness/policy/inspector/inspector_test.go, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/observer/pubsub.go, pkg/store/didanchor/store.go, test/bdd/fixtures/docker-compose.yml
- Don't use the expiry service to expire DID operations in the operation-queue. Instead, delete the operations after they fail to be delivered after the configured number of retries.
- Increase the default value for max redelivery attempts and max interval so that retries occur for an extended period of time
closes #1395
closes #1396
=> fix: Fix for lost DIDs after domain down for long period

cmd/orb-server/startcmd/start.go, pkg/anchor/anchorlinkset/anchorlinkset.go, pkg/anchor/anchorlinkset/anchorlinkset_test.go, pkg/anchor/anchorlinkset/generator/didorbgenerator/didorbgenerator.go, pkg/anchor/anchorlinkset/generator/didorbgenerator/didorbgenerator_test.go, pkg/anchor/anchorlinkset/generator/didorbtestgenerator/didorbtestgenerator.go, pkg/anchor/anchorlinkset/generator/didorbtestgenerator/didorbtestgenerator_test.go, pkg/anchor/anchorlinkset/generator/generatorregistry.go, pkg/anchor/builder/builder.go, pkg/anchor/builder/builder_test.go, pkg/anchor/graph/graph.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/util/util_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/internal/testutil/testutil.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/orbclient/aoprovider/anchororiginprovider.go, pkg/orbclient/aoprovider/anchororiginprovider_test.go
The credialSubject field in the anchor credential now has:
- id - hashlink of the original content
- anchor - the core index file hashlink
- profile - the ID of the generator that generated the content
When an anchor event is processed, the anchor credential subject is validated against the content.
closes #1348
=> feat: Add anchor and profile to anchor credential subject

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/did_orb_steps.go, test/bdd/features/orb-driver.feature, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core, disable orb-driver-test for now - until aries-framework-go-ext is updated.
Closes #1404
=> chore: Update sidetree-core (alsoKnownAs)

cmd/orb-cli/createdidcmd/createdid.go, cmd/orb-cli/createdidcmd/createdid_test.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/recoverdidcmd/recoverdid_test.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-cli/updatedidcmd/updatedid_test.go, test/bdd/cli_steps.go
Update CLI to add AlsoKnownAs
Closes #1412
=> feat: Update CLI to add AlsoKnownAs

cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/logcmd/log.go, cmd/orb-cli/logcmd/updatecmd.go, cmd/orb-cli/logcmd/updatecmd_test.go, cmd/orb-cli/witnesscmd/witness.go
=> feat: add orb-cli log update retries

cmd/orb-cli/common/activitypubclient.go, cmd/orb-cli/common/activitypubclient_test.go, cmd/orb-cli/common/common.go, cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/followcmd/follow_test.go, cmd/orb-cli/witnesscmd/witness.go, cmd/orb-cli/witnesscmd/witness_test.go, test/bdd/bddtests_test.go, test/bdd/cli_steps.go, test/bdd/common_steps.go, test/bdd/features/orb-cli.feature, test/bdd/httpclient.go
For the follow and invite-witness commands, discover the actor ID and the following/witnesses endpoints from the actor at the service endpoint.
closes #1418
=> fix: Discover actor from service endpoint in orb-cli

test/bdd/bddtests_test.go, test/bdd/common_steps.go, test/bdd/did_orb_steps.go, test/bdd/features/activitypub.feature, test/bdd/features/create-dids-to-file.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/features/nodeinfo.feature, test/bdd/features/onboard-recovery.feature, test/bdd/features/orb-cli.feature, test/bdd/features/orb-driver.feature, test/bdd/features/orb-stress.feature, test/bdd/features/versions.feature, test/bdd/httpclient.go, test/bdd/state.go, test/bdd/workerpool.go
Refactor BDD tests to remove hard-coded URLs for local host mappings, anchor origins. Also use variables in the feature files instead of repeating the entire URL many times.
closes #1420
=> refactor: Remove hard-coded URLs from BDD tests

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, internal/pkg/ldcontext/payload/activity-anchors-v1.json, pkg/activitypub/vocab/contextproperty.go, pkg/activitypub/vocab/vocab.go, pkg/anchor/builder/builder.go, pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/util/util_test.go, pkg/anchor/writer/writer.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/vcsigner/signer.go, pkg/vct/vct.go, pkg/vct/vct_test.go, samples/docker/contexts/ld-contexts.json, samples/tutorial/contexts/ld-contexts.json, test/bdd/fixtures/contexts/ld-contexts.json, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
The proof for VC now uses the jws field for VCs signed with JsonWebSignature2020. Strict validation was enabled for VC verification.
Also, updated the JSON-LD context for AnchorCredential.
closes #1435
=> fix: Invalid VC for JWS signature

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: updater to latest orb vdr

.github/workflows/build.yml, Makefile, scripts/integration_cas_ipfs.sh, scripts/integration_cas_local.sh, scripts/integration_protocol_versions.sh
=> chore: spilt bdd test runs into multi machines

pkg/document/webresolver/resolvehandler.go, pkg/document/webresolver/resolvehandler_test.go
For unpublished documents there is only one equivalent ID (with domain) so we will use that one.
For published documents we will use first (HL one).
Closes #1441
=> feat: Add equivalent ID to also known as for did:web

pkg/discovery/endpoint/restapi/operations.go
Orb did:web endpoint for file did.json should return document not resolution result
Closes #1447
=> fix: Orb did:web endpoint for file did.json should return document 

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-cli/vctcmd/verifycmd_test.go, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, internal/pkg/ldcontext/payload/activity-anchors-v1.json, pkg/anchor/anchorlinkset/generator/didorbgenerator/didorbgenerator.go, pkg/anchor/anchorlinkset/generator/didorbgenerator/didorbgenerator_test.go, pkg/anchor/anchorlinkset/generator/didorbtestgenerator/didorbtestgenerator_test.go, pkg/anchor/builder/builder.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/util/util.go, pkg/anchor/util/util_test.go, pkg/anchor/writer/writer_test.go, pkg/observer/observer_test.go, pkg/orbclient/aoprovider/anchororiginprovider_test.go, pkg/vct/vct_test.go, samples/docker/contexts/ld-contexts.json, samples/tutorial/contexts/ld-contexts.json, test/bdd/features/activitypub.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/testdata/create_activity.json, test/bdd/go.mod, test/bdd/go.sum
Added fields to credentialSubject:
- anchor
- profile
- href
- rel
- type
closes #1451
=> feat: Change credentialSubject in AnchorCredential to use fields defined in a link relation

pkg/discovery/endpoint/client/client.go
=> chore: add ipns logic to discovery getEndpoint

pkg/document/webresolver/resolvehandler.go, pkg/orbclient/doctransformer/transformer.go, pkg/orbclient/doctransformer/transformer_test.go
This function will be used by the client to verify that did:web has been created from did:orb
Closes #1465
=> feat: Move did:orb to did:web transformation code to separate function

pkg/discovery/did/mocks/endpointClient.gen.go, pkg/discovery/endpoint/client/client.go, pkg/document/mocks/endpointclient.gen.go, pkg/document/resolvehandler/resolvehandler.go
=> chore: add ipns logic in resolver

cmd/orb-server/startcmd/params_test.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber_test.go
Added a publisher channel to handle publish requests in a separate Go proc. When the HTTP subscriber is stopped, the publisher listener safely shuts down the subscriber channel.
This commit also fixes the problem with varying code coverage in the unit tests.
closes #1463
closes #591
=> fix: Panic in HTTP subscriber Stop

pkg/orbclient/doctransformer/transformer.go, pkg/orbclient/doctransformer/transformer_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
VerifyWebDocumentFromOrbDocument will create web document from orb resolution result and compare that web document with provided web document for equality.
Also, add BDD test.
Closes #1374
=> feat: Add VerifyWebDocumentFromOrbDocument to orb client

Makefile, README.md, scripts/generate_test_keys.sh, test/bdd/cli_steps.go
* BDD tests are no longer hardcoded to use the amd64 binary for CLI commands. They now select between amd64 and arm64 based on the running system's detected architecture.
* Updated the Makefile's extract-orb-cli-binaries target to extract the arm64 binaries (they were being built before but were never extracted).
* Resolved a warning from Docker that would get printed when running the generate-test-keys Makefile target on an arm64 system. The warning from Docker alerts you that the image for frapsoft/openssl is for amd64, which doesn't match the system you're on. To resolve the warning, you have to either use an image that matches the system architecture, or explicitly state the platform using the --platform flag. In this case, there is only an amd64 version of frapsoft/openssl, so I …
=> feat: Improved arm64 support, add missing docs

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-cli/vctcmd/verifycmd.go, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/vcsigner/signer.go, pkg/vcsigner/signer_test.go, pkg/vct/logmonitoring/monitor.go, pkg/vct/logmonitoring/monitor_test.go, pkg/vct/proofmonitoring/monitoring.go, pkg/vct/proofmonitoring/monitoring_test.go, pkg/vct/vct.go, pkg/vct/vct_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> fix: Only add JSON-LD contexts that are referenced in the proof

pkg/document/webresolver/resolvehandler.go, pkg/document/webresolver/resolvehandler_test.go
If port is specified for domain (external endpoint) return proper port encoding e.g. did:web:example.com%3A3000:scid:suffix
Closes #1482
=> fix: did:web resolver is not properly encoding port in DID

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/restapi/operations.go, pkg/document/util/util.go, pkg/document/util/util_test.go, pkg/document/webresolver/resolvehandler.go, pkg/document/webresolver/resolvehandler_test.go, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml
Limit resolving did:web DIDs to current host domain plus configured additional domains.
Closes #1475
=> feat: did:web resolver should allow resolving DIDs that have different domain in DID if configured

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml
The issuer in the anchor credential (VC) is now always the same as the author of the anchor linkset. So if the auther is a DID then the issuer will be set to the same DID.
This commit also removes the startup parameters, anchor-credential-issuer and anchor-credential-url since they are redundant and can also lead to misconfiguration.
closes #1488
=> fix: Make VC issuer the same as author of anchor linkset

cmd/orb-cli/acceptlistcmd/getcmd.go, cmd/orb-cli/acceptlistcmd/updatecmd.go, cmd/orb-cli/allowedoriginscmd/getcmd.go, cmd/orb-cli/allowedoriginscmd/updatecmd.go, cmd/orb-cli/common/activitypubclient.go, cmd/orb-cli/common/common.go, cmd/orb-cli/createdidcmd/createdid.go, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/ipfskeygencmd/keygen.go, cmd/orb-cli/ipnshostmetagencmd/ipnshostmetagencmd.go, cmd/orb-cli/ipnshostmetauploadcmd/ipnshostmetauploadcmd.go, cmd/orb-cli/logcmd/getcmd.go, cmd/orb-cli/logcmd/updatecmd.go, cmd/orb-cli/logmonitorcmd/getcmd.go, cmd/orb-cli/logmonitorcmd/updatecmd.go, cmd/orb-cli/policycmd/getcmd.go, cmd/orb-cli/policycmd/updatecmd.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/resolvedidcmd/resolvedid.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-cli/vctcmd/verifycmd.go, cmd/orb-cli/witnesscmd/witness.go, cmd/orb-driver/startcmd/start.go, cmd/orb-server/startcmd/params.go, go.mod, go.sum, internal/pkg/cmdutil/cmdutil.go, internal/pkg/cmdutil/cmdutil_test.go
Moved the command utility functions to an internal package in orb.
closes #1492
=> chore: Remove dependency on edge-core cmdutils

cmd/orb-cli/common/common.go, cmd/orb-cli/createdidcmd/createdid.go, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/ipfskeygencmd/keygen.go, cmd/orb-cli/ipnshostmetagencmd/ipnshostmetagencmd.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/resolvedidcmd/resolvedid.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-driver/startcmd/start.go, cmd/orb-server/startcmd/start.go, internal/pkg/tlsutil/certpool.go, internal/pkg/tlsutil/certpool_test.go, internal/pkg/tlsutil/tlsutil.go, internal/pkg/tlsutil/tlsutil_test.go
Moved tlsutils functions to internal orb package.
closes #1493
=> chore: Remove dependency on edge-core tlsutils

cmd/orb-server/startcmd/start.go, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/anchor/handler/credential/handler.go, pkg/context/protocol/client/client.go, pkg/driver/restapi/operations.go, pkg/httpserver/auth/authwrapper.go, pkg/httpserver/auth/signature/authwrapper.go, pkg/httpserver/auth/tokenverifier.go, pkg/httpserver/server.go, pkg/lifecycle/lifecycle.go, pkg/nodeinfo/handler.go, pkg/nodeinfo/handler_test.go, pkg/nodeinfo/service.go, pkg/nodeinfo/service_test.go, pkg/observer/observer.go, pkg/observer/pubsub.go, pkg/orbclient/aoprovider/anchororiginprovider.go, pkg/orbclient/protocol/verprovider/versionprovider.go, pkg/protocolversion/clientregistry/clientregistry.go, pkg/protocolversion/factoryregistry/factoryregistry.go, pkg/protocolversion/versions/v1_0/factory/factory.go
Implemented structured logging for the following subsystems:
- context
- driver
- httpserver
- lifecycle
- nodeinfo
- observer
- orbclient
- protocolversion
=> chore: Convert subsystems to use structured logs

cmd/orb-server/startcmd/start.go
=> chore: Remove LD context REST endpoints

pkg/httpserver/auth/tokenverifier.go, test/bdd/fixtures/docker-compose.yml
Also cleaned up the auth token definition in the BDD test to remove invalid endpoint.
closes #1523
=> fix: Panic in auth handler for DELETE and PUT methods

.github/workflows/build.yml, Makefile, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/healthcheck/healthcheck.go, pkg/healthcheck/healthcheck_test.go, pkg/httpserver/maintenance/mode.go, pkg/httpserver/maintenance/mode_test.go, scripts/integration_versions_maintenance.sh, test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose-testver.yml
Add maintenance mode flag to server startup parameters.
In case that maintenance mode is set:
-- disable Sidetree operations and identifiers endpoints 
-- disable Activity Pub inbox endpoint
-- return 200 (or some special status) for health-check
Closes #1527
=> feat: Implement maintenance mode (configurable)

pkg/orbclient/resolutionverifier/resolutionverifier.go, pkg/orbclient/resolutionverifier/resolutionverifier_test.go, test/bdd/features/did-orb.feature
Input and resolved documents are the same however metadata check fails due to missing updateCommitment.
We should not be checking commitments for deactivated document since they are not available.
Closes #1529
=> fix: Orb client document verification fails for deactivated document

cmd/orb-server/startcmd/log.go, cmd/orb-server/startcmd/log_test.go, cmd/orb-server/startcmd/start.go, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, test/bdd/common_steps.go, test/bdd/features/loglevels.feature, test/bdd/fixtures/docker-compose.yml
The /loglevels endpoints allows you to update the logging levels dynamically and retrieve the current levels.
=> feat: Added /loglevels REST endpoint

.golangci.yml, cmd/orb-server/main.go, cmd/orb-server/startcmd/log_test.go, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, internal/pkg/cmdutil/cmdutil.go, internal/pkg/cmdutil/cmdutil_test.go, scripts/check_lint.sh
The golangci-linter was enabled in cmd/orb-server which required extensive refactoring of the code.
=> refactor: Enable linter in orb-server

pkg/vct/logmonitoring/monitor.go, pkg/vct/logmonitoring/monitor_test.go
Invalid range calculation for getting entries in log monitor
Closes #1542
=> fix: Invalid range calculation for getting entries in log monitor

pkg/activitypub/service/acceptlist/acceptlist.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/anchorsynctask/activitysynctask.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/store/ariesstore/ariesstore.go, pkg/anchor/allowedorigins/allowedoriginsmgr/allowedoriginsmgr.go, pkg/anchor/linkstore/linkstore.go, pkg/nodeinfo/service.go, pkg/store/anchorstatus/store.go, pkg/store/expiry/expiry.go, pkg/store/logentry/store.go, pkg/store/logmonitor/store.go, pkg/store/operation/store.go, pkg/store/operation/unpublished/store.go, pkg/store/store.go, pkg/vct/logmonitoring/monitor.go
Close various DB iterators after use.
=> fix: MongoDB cursor leak

pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/outbox/outbox.go, pkg/context/opqueue/opqueue.go, pkg/errors/errors.go, pkg/observer/pubsub.go
Handlers for pooled subscribers are each executed in a separate Go routine.
Also fixed a race condition in the errors util.
closes #1552
=> fix: Execute pooled MQ handler in separate Go routine

pkg/store/expiry/expiry.go, pkg/store/expiry/expiry_test.go
=> fix: Limit the number of documents deleted per batch

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/vcpubsub/publisher.go, pkg/anchor/vcpubsub/subscriber.go, pkg/anchor/vcpubsub/vcpubsub_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
=> feat: Enable subscriber pool for orb.anchor_linkset queue

cmd/orb-server/startcmd/start.go, internal/pkg/log/fields.go, pkg/activitypub/client/client.go, pkg/activitypub/client/client_test.go, pkg/cache/cache.go, pkg/cache/cache_test.go
The ActivityPub actor and public key caches are refreshed in the background so as not to affect the performance of a client call. If the refresh fails (due to the server being down) then the old value continues to be used.
closes #1551
=> feat: Background refresh of actor/public key cache

cmd/orb-server/startcmd/params.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/witness/policy/inspector/inspector.go, pkg/anchor/witness/policy/selector/random/selector.go, pkg/anchor/witness/policy/selector/random/selector_test.go, pkg/anchor/writer/writer.go, pkg/document/updatehandler/decorator/decorator.go, pkg/store/anchorstatus/store.go, pkg/store/anchorstatus/store_test.go, pkg/vct/logmonitoring/monitor.go
The anchor monitor process will remove all in-process anchor status records after all witnesses have been exhausted.
This commit also adds more information to existing logs (such as anchorUri) and changes the level from DEBUG to INFO for some of the important logs so that issues may be more easily debugged.
=> fix: Stop monitoring anchor once witness list is exhausted

cmd/orb-server/startcmd/params.go, pkg/context/opqueue/opqueue.go
=> fix: Set expiryTime field on detached operation

pkg/activitypub/httpsig/signer.go, pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/linkstore/linkstore.go, pkg/anchor/linkstore/linkstore_test.go, pkg/mocks/anchorlinkstore.gen.go, pkg/observer/observer.go, pkg/observer/observer_test.go
Just before posting an anchor to the message queue, check if the anchor has already been processed. This greatly reduces the number of duplicate anchors sent to the queue and will improve overall performance.
closes #1565
=> fix: Don't process anchor if it has already been processed

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/cache/cache_test.go, pkg/store/witness/witness.go, pkg/vct/proofmonitoring/monitoring.go, pkg/vct/proofmonitoring/monitoring_test.go
Also limit the number of records to check per monitor interval.
closes #1563
closes #1570 
closes #1569
=> fix: Exit proof monitor loop on server shutdown

pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/handler/mocks/anchorlinkstore.gen.go
=> fix: Delete pending anchor link references when failed to publish to queue

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/internal/testutil/testutil.go, pkg/store/anchorstatus/store.go, pkg/store/anchorstatus/store_test.go, pkg/vct/proofmonitoring/monitoring.go, scripts/check_lint.sh
Also, updated witness proof monitor to accelerate the next task time if it is known that more records need to be processed.
closes #1572
=> fix: Exit anchor status monitoring loop on shutdown

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/context/opqueue/opqueue.go, test/bdd/go.mod, test/bdd/go.sum
Updated to latest sidetree-core-go which fixes this issue.
See https://github.com/trustbloc/sidetree-core-go/issues/697 for details.
closes #1579
=> fix: Failed processing of batch can cause operation queue to grow uncontrollably

pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go
This function bypasses the cache when retrieving the sidetree endpoint for the domain.
=> chore: Add function GetEndpointNoCache
