trustbloc/orb

.golangci.yml, cmd/orb-server/main.go, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/txnclient/client.go, pkg/context/txnclient/client_test.go, pkg/observer/observer_test.go, pkg/txngraph/graph.go, pkg/txngraph/graph_test.go, test/bdd/go.mod
Included:
- Txn Client signs anchor credential using kms key
- Observer verifies signature using kms public key fetcher
- Various typo fixes
Closese #22
=> feat: Sign Orb Transaction

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/context/txnclient/client.go, pkg/context/txnclient/client_test.go, pkg/vcbuilder/builder.go, pkg/vcbuilder/builder_test.go, pkg/vcsigner/signer.go, pkg/vcsigner/signer_test.go, test/bdd/fixtures/docker-compose.yml
Add anchor credential builder that will build and sign anchor credential.
Configure anchor credential parameters for orb-server.
Closes #24
=> feat: Add anchor credential builder

pkg/activitypub/vocab/contextproperty.go, pkg/activitypub/vocab/contextproperty_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, pkg/activitypub/vocab/typeproperty.go, pkg/activitypub/vocab/typeproperty_test.go, pkg/activitypub/vocab/urlproperty.go, pkg/activitypub/vocab/urlproperty_test.go
=> chore: Remove Get prefix from local property accessors

pkg/activitypub/vocab/collection.go, pkg/activitypub/vocab/collection_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go
Implemented the Collection and OrderedCollection types and added support for embedding Collection and OrderedCollection in the 'object' property.
closes #30
=> feat: Implemented Collection and OrderedCollection types

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/context/txnclient/client.go, pkg/didtxnref/memdidtxnref/refs.go, pkg/didtxnref/refs.go, pkg/mocks/protocol.go, pkg/versions/0_1/operationparser/parser.go, pkg/versions/0_1/operationparser/parser_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature, test/bdd/go.mod, test/bdd/go.sum
Included:
- add CID to canonical ID in resolution result
- resolve did using canonical ID
- set/change canonical ID during create/recover
Closes #27
=> feat: handle CID as part of DID

pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go
Implemented the base Activity type object and also the following activity types:
- Create
- Announce
- Follow
- Accept
- Reject
- Like
closes #31
=> feat: Implemented the basic activity types

pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchorcredreftype.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab_test.go
Implemented the ActivityPub "Offer" activity type and the "AnchorCredentialReference" object type.
closes #34
=> feat: Implemented Offer activity and AnchorCredentialReference

pkg/activitypub/vocab/actor.go, pkg/activitypub/vocab/actor_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go
=> feat: Implemented base Actor and Service actor type

cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: update aries-framework-go revision

pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/lifecycle/lifecycle.go, pkg/activitypub/service/lifecycle/lifecycle_test.go, pkg/activitypub/service/outbox/httppublisher/httppublisher.go, pkg/activitypub/service/outbox/httppublisher/httppublisher_test.go
This commit adds an HTTP implementation of a Watermill Publisher.
closes #62
=> feat: Implement HTTP Publisher for Watermill

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/builder/builder.go, pkg/anchor/builder/builder_test.go, test/bdd/fixtures/docker-compose.yml
Generate id for anchor credential based on configured URL and uuid.
Clsoes #89
=> feat: Add id to anchor credential

cmd/orb-server/startcmd/start.go, go.mod, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
Store anchor credential before sending for witnessing.
Closes #92
=> feat: Store anchor credential

cmd/orb-server/startcmd/start.go, pkg/activitypub/resthandler/resthandler.go, pkg/activitypub/resthandler/resthandler_test.go, pkg/activitypub/resthandler/serviceshandler.go, pkg/activitypub/resthandler/serviceshandler_test.go
Implemented a REST endpoint that returns an ActivityPub service (actor).
closes #102
=> feat: Services REST endpoint

pkg/activitypub/vocab/collection.go, pkg/activitypub/vocab/collection_test.go, pkg/activitypub/vocab/collectionpage.go, pkg/activitypub/vocab/collectionpage_test.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab.go
Implemented the CollectionPage and OrderedCollectionPage ActivityPub types.
closes #105
=> feat: Added support for CollectionPage and OrderedCollectionPage

pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/activitystore.gen.go, pkg/activitypub/store/memstore/iterator.go, pkg/activitypub/store/memstore/iterator_test.go, pkg/activitypub/store/memstore/memstore.go, pkg/activitypub/store/memstore/memstore_test.go, pkg/activitypub/store/spi/spi.go, pkg/activitypub/store/storeutil/storeutil.go, pkg/activitypub/store/storeutil/storeutil_test.go
Paging and sorting options were added to the QueryActivities function. Sorting is either ascending (default) or descending. Paging options were also added: page number and page size.
closes #110
=> feat: Added paging and sorting to activity query

pkg/activitypub/resthandler/activityhandler.go, pkg/activitypub/resthandler/referencehandler.go
Removed unnecessary structs that didn't add any value.
closes #149
=> refactor: Eliminated unnecessary structs in ActivityPub REST handlers

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/anchor/graph/graph.go, pkg/anchor/graph/graph_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go, test/bdd/go.mod, test/bdd/go.sum
Transaction Processor: Add ability to process batch files for requested DIDs.
Observer: Add channel to request processing DIDs from batch files.
Closes #153
=> feat: Process batch files for requested DIDs

pkg/activitypub/resthandler/activityhandler_test.go, pkg/activitypub/resthandler/serviceshandler_test.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/actortype_test.go, pkg/activitypub/vocab/anchorcredreftype_test.go, pkg/activitypub/vocab/objectproperty_test.go, pkg/activitypub/vocab/objecttype_test.go, pkg/activitypub/vocab/vocab.go
Changed Orb context to https://trustbloc.github.io/did-method-orb/contexts/anchor/v1
closes #126
=> chore: Change Orb context

test/bdd/bddtests_test.go, test/bdd/common_steps.go, test/bdd/compose.go, test/bdd/did_orb_steps.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/httpclient.go, test/bdd/state.go, test/bdd/utils.go
Added generic steps to the BDD test for getting/posting HTTP requests and examining JSON responses using JSONPath syntax.
closes #162
=> test: Added HTTP and JSONPath BDD steps

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, test/bdd/fixtures/docker-compose.yml
Configure batch writer timeout (max time in-between cutting batches)
Closes #164
=> chore: Configure batch writer timeout

cmd/orb-server/startcmd/start.go, pkg/anchor/handler/credential.go, pkg/anchor/handler/credential_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/context/cas/ipfs.go, pkg/observer/observer.go, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml
Create:
- anchor credential activity
- anchor credential handler
Closes #189
=> feat: Create anchor credential activity and handler

pkg/activitypub/client/client.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/mockpubsub.go, pkg/activitypub/service/outbox/httppublisher/httppublisher.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/redelivery/redelivery.go, pkg/activitypub/service/outbox/redelivery/redelivery_test.go, pkg/activitypub/vocab/objecttype.go, pkg/httpserver/server.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, test/bdd/common_steps.go, test/bdd/did_orb_steps.go
=> chore: Remove references to package "github.com/pkg/errors"

pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockanchorcredhandler.go, pkg/activitypub/service/spi/spi.go, pkg/anchor/handler/credential.go, pkg/anchor/handler/credential_test.go, pkg/observer/observer.go
Add cid to anchor handler interface.
Closes #200
=> chore: Add cid to anchor handler interface

test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Add url to did requests.
Also, add check for anchor processing on 'follower' server.
Closes #191
=> chore: add url to did requests (identifiers/operations)

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/docker-compose.yml
=> feat: add configuration for discovery domains

cmd/orb-server/startcmd/params.go
=> fix: didAliasesFlag arg

pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/mocks/mockpubsub.go, test/bdd/common_steps.go
Modified the mock pub-sub to copy the Watermill message so that multiple Acks/Nacks are not posted to the same message. Also added more debug logs.
closes #204
=> fix: Inbox unit test failure

test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
BDD Test: missed resolve URL
Closes #210
=> fix: Missed resolve URL (BDD)

cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/anchor/builder/builder.go, pkg/anchor/builder/builder_test.go, pkg/vcsigner/signer.go, pkg/vcsigner/signer_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
=> feat: Adds proof (witness)

pkg/store/operation/store.go, pkg/store/operation/store_test.go
Configure operation store index
Closes #236
=> chore: configure operation store index

cmd/orb-server/go.mod, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go
=> feat: Adds monitoring

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
=> fix: Handle Reject of InviteWitness

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
Check the 'following' and 'witnesses' collections for the actor in the 'Accept' handler. If the actor already exists in the collection then the activity is rejected.
closes #260
=> fix: Ensure that a witness and/or following is added only once

pkg/activitypub/service/mempubsub/mempubsub.go, pkg/activitypub/service/mempubsub/mempubsub_test.go
=> fix: Data race in mem PubSub on close

pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go
Add witness proof to anchor credential
Closes #264
=> chore: add witness proof to anchor credential

test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Configure anchor origin per server, add external to internal server mapping.
Closes #261
=> chore: Configure anchor origin per server

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, test/bdd/bddtests_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/scripts/create_kms_store.sh
=> feat: Adds webkms support

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature
Add retry to document tests
Closes #283
=> chore: add retry to did document tests

test/bdd/fixtures/docker-compose.yml
=> chore: Updates web kms

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
When a 'Create' is handled then the activity is announced to the service's followers. A check is made to ensure that an 'Announce' activity is not sent back to the originator of the 'Create'.
closes #278
=> fix: Don't announce anchor credential to the actor of the 'Create'

test/bdd/fixtures/docker-compose.yml
=> chore: Adds docker tags

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature
Add checks for did operation(update, recover, deactivate) success in tests.
Closes #291
=> chore: Add checks for did operation success in tests

cmd/orb-server/startcmd/start.go, go.mod, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/discovery/endpoint/restapi/model.go, pkg/discovery/endpoint/restapi/openapi.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, scripts/generate_test_keys.sh, test/bdd/fixtures/docker-compose.yml
=> feat: Adds did web support

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/restclient/sender.go, test/bdd/workerpool.go
Create multiple concurrent DIDs in domains 1 and 2 and then randomly retrieve them from servers in domains 1 and 2.
Closes #296
=> chore: Test creating multiple concurrent DIDs

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature
Test flow:
- create batch of DIDs
- re-start servers in domain1 and domain2
- check for previously created DIDs
- create another batch of DIDs and check them
Closes #306
=> chore: Add orb re-start test

pkg/activitypub/store/ariesstore/ariesstore_internal_test.go, pkg/activitypub/store/ariesstore/ariesstore_test.go
=> test: More ActivityPub Aries storage tests

test/bdd/features/did-orb.feature
=> test: Fix BDD tests

pkg/activitypub/store/ariesstore/ariesstore.go, pkg/activitypub/store/ariesstore/ariesstore_test.go
=> fix: Panic in iterator when no references found in an activity query

cmd/orb-server/startcmd/start.go
Now that we support did:web we can replace custom public key fetcher with aries version.
Closes #314
=> chore: Replace custom public key fetcher with aries version

.github/workflows/build.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> ci: bump semver when publishing snapshot

cmd/orb-server/startcmd/start.go, pkg/anchor/builder/builder.go, pkg/context/loader/context.go, pkg/internal/testutil/testutil.go, pkg/vcsigner/signer_test.go
=> feat: Removes remote document loader

cmd/orb-server/startcmd/start.go, pkg/context/cas/ipfs/ipfs.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, pkg/webcas/webcas.go, pkg/webcas/webcas_internal_test.go, pkg/webcas/webcas_test.go
=> feat: WebCAS

cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
=> chore: Updates VCT version

README.md
=> docs: Instructions for setting up witnesses and followers

.github/workflows/publish.yaml, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
=> chore: update vct image tag

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml
Add delay for starting additional servers within domain
Closes #337
=> chore: Add delay for starting additional servers within domain

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
When processing an 'Accept', the original 'Follow' or 'InviteWitness' activity is loaded from the service's outbox and validated to ensure that it exists and is the same as the target of the 'Accept', otherwise the Accept is rejected since it could be an attempt to add an unsolicited follower or witness.
closes #302
=> feat: Validate original activity in 'Accept'

cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/recoverdidcmd/recoverdid_test.go
=> feat: add did recover cmd

.gitignore, Makefile, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/deactivatedidcmd/deactivatedid_test.go, cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-cli/main.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/recoverdidcmd/recoverdid_test.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-cli/updatedidcmd/updatedid_test.go, scripts/generate_test_keys.sh, test/bdd/bddtests_test.go, test/bdd/cli_steps.go, test/bdd/features/orb-cli.feature, test/bdd/fixtures/did-keys/create/key1_jwk.json, test/bdd/fixtures/did-keys/create/key2_jwk.json, test/bdd/fixtures/did-keys/create/publickeys.json, test/bdd/fixtures/did-keys/recover/key1_jwk.json, test/bdd/fixtures/did-keys/recover/publickeys.json, test/bdd/fixtures/did-keys/update/key2_jwk.json, test/bdd/fixtures/did-keys/update/key3_jwk.json, test/bdd/fixtures/did-keys/update/publickeys.json, test/bdd/fixtures/did-services/create/services.json, test/bdd/fixtures/did-services/recover/services.json, test/bdd/fixtures/did-services/update/services.json, test/bdd/go.sum
=> test: add bdd test for orb cli

cmd/orb-server/startcmd/start.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/store/witness/witness.go
Store witness proof in proof handler.
Closes #367
=> chore: store witness proof in proof handler

cmd/orb-cli/common/common.go, cmd/orb-cli/common/common_test.go, cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/followcmd/follow_test.go, cmd/orb-cli/go.mod, cmd/orb-cli/main.go
=> feat: add follow cmd

cmd/orb-cli/main.go, cmd/orb-cli/witnesscmd/witness.go, cmd/orb-cli/witnesscmd/witness_test.go, test/bdd/cli_steps.go, test/bdd/features/orb-cli.feature
=> feat: add witness cmd

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update aries revision

.github/workflows/build.yml, .github/workflows/publish.yaml
=> chore: add upload artifact

.github/workflows/build.yml
=> fix: add go 16 to publish job

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, pkg/activitypub/resthandler/activityhandler.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/docker-compose.yml
=> fix: Panic if read token not specified alongside write token

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Add support for interim hint for unpublished documents (result of create) and long-form DID.
Closes #400
=> feat: Add support for interim/domain hint for create result and long-form DID

cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/restapi/model.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go
=> feat: WebFinger support for getting WebCAS URL

.github/workflows/build.yml, .github/workflows/publish.yaml, Makefile, cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-driver/startcmd/start.go, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, images/orb-driver/Dockerfile, pkg/context/loader/context.go, pkg/internal/testutil/testutil.go, test/bdd/bddtests_test.go, test/bdd/context.go, test/bdd/did_orb_steps.go, test/bdd/driver_steps.go, test/bdd/features/orb-driver.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/uni-resolver-web/config.json, test/bdd/go.mod, test/bdd/go.sum
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> test: add bdd test for universal resolver driver

pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/observer/observer.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go
=> feat: Resolver support for resolving WebCAS URLs via WebFinger

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/mocks/mockproofhandler.go, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/activitypub/service/spi/spi.go, pkg/anchor/handler/credential/handler.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/handler/mocks/monitoring.gen.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
=> feat: Anchor credential monitoring

cmd/orb-server/startcmd/start.go, pkg/resolver/document/resolvehandler.go, pkg/resolver/document/resolvehandler_test.go
Ignore interim dids for did discovery
Closes #447
=> fix: Exclude interim did from did discovery

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/fixtures/docker-compose.yml
=> feat: Added a possibility to run the service without VCT.

cmd/orb-cli/go.mod, cmd/orb-cli/ipnswebfingeruploadcmd/webfingerupload.go, cmd/orb-cli/ipnswebfingeruploadcmd/webfingerupload_test.go, cmd/orb-cli/main.go
=> feat: add cmd to upload webfinger to ipns

pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go
=> refactor: ipns webfinger docment

.gitignore, test/bdd/driver_steps.go, test/bdd/fixtures/docker-compose.yml
=> fix: ipfs docker ports

cmd/orb-cli/ipfskeygencmd/keygen.go, cmd/orb-cli/ipfskeygencmd/keygen_test.go
=> feat: add ability to import key to ipfs

cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/didanchor/memdidanchor/store.go, pkg/didanchor/memdidanchor/store_test.go, pkg/didanchor/refs.go, pkg/didanchor/resthandler/didanchor.go, pkg/didanchor/resthandler/didanchor_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, pkg/store/didanchor/store.go, pkg/store/didanchor/store_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Add REST endpoint for getting the latest anchor for suffix.
Closes #483
=> feat: Add REST endpoint for getting the latest anchor for suffix

pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go
Also changed existing base URL resource to return Orb services URL directly.
=> feat: Add Witness WebFinger resource

cmd/orb-server/startcmd/start.go, pkg/didorigin/resthandler/didorigin.go, pkg/didorigin/resthandler/didorigin_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Add REST endpoint for getting latest anchor origin for suffix
Closes #493
=> feat: Add REST endpoint for getting latest anchor origin for suffix

pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go
=> feat: add anchor and origin webfinger resource

.github/workflows/build.yml
=> chore: upload bdd logs

cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/discovery/endpoint/restapi/operations.go
=> feat: Support for resolving anchor origin via IPNS

pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/store/witness/witness.go, pkg/store/witness/witness_test.go
Delete witness policy transient data (data from witness store).
Closes #452
=> chore: delete witness policy transient data

pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go
Handle the case when proof comes after expiry time.
Closes #451
=> chore: Witness policy -  handle expired proofs

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/anchor/graph/graph.go, test/bdd/go.mod, test/bdd/go.sum
Canonicalize anchor credential before storing to CAS
Closes #508
=> chore: Canonicalize anchor credential before storing to CAS

.github/workflows/build.yml
=> chore: fix upload logs

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update sidetree-core version

scripts/generate_test_keys.sh, test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Add domain3 and domain4 to TLS certificate.
Closes #540
=> chore: Add domain3 and domain4 to TLS certificate

pkg/anchor/vcpubsub/subscriber.go, pkg/pubsub/amqp/pooledsubscriber.go, pkg/pubsub/amqp/pooledsubscriber_test.go
Fixes a race condition that occasionally occurs in the pooled subscriber stop function.
closes #542
=> fix: Race condition in AMQP pooled subscriber

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go
=> feat: Added ActivityPub page size startup parameter

cmd/orb-server/startcmd/start.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Check that requested CID in DID belongs to resolved document
Closes #429
=> feat: Check that requested CID in DID belongs to resolved document

cmd/orb-cli/ipnshostmetagencmd/ipnshostmetagencmd.go, cmd/orb-cli/ipnshostmetagencmd/ipnshostmetagencmd_test.go, cmd/orb-cli/ipnshostmetauploadcmd/ipnshostmetauploadcmd.go, cmd/orb-cli/ipnshostmetauploadcmd/ipnshostmetauploadcmd_test.go, cmd/orb-cli/main.go, cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/discovery/endpoint/restapi/model.go, pkg/discovery/endpoint/restapi/openapi.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/resolver/resource/resolver.go, pkg/resolver/resource/resolver_test.go, test/bdd/did_orb_steps.go
- Reworked existing WebFinger implementation and added host-meta endpoint to replace some of that functionality.
- Updated CLI commands.
=> feat: Rework WebFinger Implementation

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
Update the 'shares' collection when the 'Announce' activity is received in the inbox. Previously it was updated when the 'Announce' was posted to the outbox.
closes #277
=> fix: Update 'shares' collection during handling of the 'Announce'

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum
=> chore: update to latest orb

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, test/bdd/bddtests_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
Added webfinger to discover vct.
`curl http://orb.com/.well-known/webfinger?resource=http://orb.com/vct`
Response: 
```
{
"subject":"http://base/vct",
"links":[
{
"rel":"self",
"href":"http://base/vct"
},
{
"rel":"vct",
"type":"application/jrd+json",
"href":"http://vct.com"
},
{
"rel":"vct+alternate",
"type":"application/jrd+json",
"href":"http://vct.com/maple2020"
}
]
}
```
=> feat: Updates vct (webfinger usage)

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, test/bdd/fixtures/docker-compose.yml
=> feat: add ability to import orb private key

pkg/cas/ipfs/ipfs.go
=> fix: ipfs log

pkg/pubsub/amqp/amqppubsub.go
The backoff parameters for AMQP connections were adjusted such that retry intervals were reduced but maximum retries were increased. This allows for quicker connection to the AMQP broker.
closes #556
=> chore: Reduce AMQP connection retry intervals

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest aries

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/monitoring/monitoring.go, pkg/activitypub/service/monitoring/monitoring_test.go, pkg/activitypub/service/vct/vct.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, test/bdd/fixtures/docker-compose.yml
=> feat: Updates webfinger usage

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum
=> chore: update to vct 0.1.2 release

cmd/orb-driver/main.go, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/nginx-config/nginx.conf
=> feat: Adds load balancer to demonstrate horizontal scaling

cmd/orb-server/startcmd/params.go, test/bdd/bddtests_test.go, test/bdd/fixtures/docker-compose.yml
=> fix: bdd test

.github/workflows/build.yml, cmd/orb-server/startcmd/start.go, test/bdd/bddtests_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/nginx-config/nginx.conf
=> fix: Fixes error message

.github/workflows/build.yml, test/bdd/bddtests_test.go, test/bdd/features/orb-stress.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/stress_steps.go
=> test: add orb stress test

test/bdd/stress_steps.go
=> feat: add configurable max retry for orb stress test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/errors/errors.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, pkg/webcas/webcas.go, pkg/webcas/webcas_internal_test.go, pkg/webcas/webcas_test.go, test/bdd/fixtures/docker-compose.yml
Added support for replicating local CAS writes to IPFS.
closes #399
=> feat: Support for replicating local CAS writes to IPFS

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/anchor/writer/writer_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver_test.go, pkg/resolver/resource/resolver_test.go, pkg/store/cas/cas_test.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/docker-compose.yml
Also fixed the orb-kms container to work with Docker 3.5.2.
closes #594
=> chore: Add IPFS timeout startup parameter

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver.go, pkg/cas/resolver/resolver_test.go, pkg/resolver/resource/resolver.go, pkg/resolver/resource/resolver_test.go
Also fixed a scenario where a nil pointer exception can occur when the IPFS URL is not set.
closes #603 
closes #531
=> feat: Allow IPFS to be optional

cmd/orb-cli/go.sum, cmd/orb-driver/go.sum, cmd/orb-server/startcmd/start.go, pkg/activitypub/client/client.go, pkg/activitypub/client/client_test.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go
=> feat: Add actor, public key, and outbox IRI cache

cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go, pkg/metrics/handler.go, pkg/metrics/handler_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/MetricsProvider.go
This commit also exposes the /metrics endpoint for statistics.
closes #623
=> chore: Added metrics for ActivityPub using Prometheus

test/bdd/stress_steps.go
=> chore: fix stress test log

pkg/metrics/metrics.go, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/prometheus-config/prometheus.yml
Only domain2 servers were instrumented (for now) since they don't require TLS.
closes #628
=> chore: Added sample Prometheus server to BDD test

cmd/orb-server/startcmd/start.go, pkg/anchor/vcpubsub/subscriber.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/metrics/metrics.go, pkg/mocks/MetricsProvider.go
=> chore: Add metrics for batch writer

cmd/orb-server/startcmd/start.go, pkg/context/opqueue/opqueue.go, pkg/context/opqueue/opqueue_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/MetricsProvider.go, pkg/observer/observer.go, pkg/observer/observer_test.go
=> chore: Added metrics for Observer and Operation queue

test/bdd/stress_steps.go
=> chore: reoslve did's after create for stress test

test/bdd/stress_steps.go
=> chore: update stress test to check if did is published

pkg/multihash/multihash.go, pkg/multihash/multihash_test.go
=> feat: Added function to convert multihash to V0 CID

cmd/orb-server/startcmd/start.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, pkg/document/updatehandler/updatehandler.go, pkg/document/updatehandler/updatehandler_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, test/bdd/did_orb_steps.go, test/bdd/fixtures/nginx-config/nginx.conf
=> chore: Add metrics for document REST handlers: create/update & resolve

pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/service.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
Added Prometheus metrics for counts of activities, per activity type.
closes #639
=> chore: Added metrics for count of activities

test/bdd/bddtests_test.go
=> chore: update test sleep

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph_test.go, pkg/anchor/handler/credential/handler_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/resolver/resolver_test.go, pkg/metrics/metrics.go, pkg/mocks/metricsprovider.go, pkg/multihash/multihash_test.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, pkg/webcas/webcas_internal_test.go, pkg/webcas/webcas_test.go
Also added metrics for cache hits/misses.
closes #655
=> feat: Cache for local CAS storage

pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/service.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
=> chore: Changed inbox handler time metric to be per activity type

pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
=> chore: Better log message for 'no witnesses' error in batch writer

test/bdd/stress_steps.go
=> chore: add update DID to stress test

test/bdd/stress_steps.go
=> chore: disable resolve update

test/bdd/stress_steps.go
=> chore: add failed msg for update

cmd/orb-server/startcmd/start.go, pkg/anchor/graph/graph_test.go, pkg/anchor/writer/writer_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/ipfs/ipfs_test.go, pkg/cas/resolver/resolver_test.go, pkg/context/opqueue/opqueue.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, pkg/resolver/resource/resolver_test.go, pkg/store/cas/cas.go, pkg/store/cas/cas_test.go, test/bdd/did_orb_steps.go
Added an IPFS cache as well as metrics for IPFS read/write times.
closes #660
=> feat: Cache for IPFS

cmd/orb-server/startcmd/start.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/store/wrapper/provider.go, pkg/store/wrapper/provider_test.go, pkg/store/wrapper/store.go, pkg/store/wrapper/store_test.go
=> chore: Added db metric

pkg/anchor/writer/writer.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
=> chore: add details metric for build credential

pkg/anchor/writer/writer.go, pkg/store/wrapper/store.go
=> fix: metrics

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core and add https: to domain.
Closes #678
=> chore: Switch the order of interim label and domain.

README.md
=> docs: Database backup and startup options

pkg/anchor/writer/writer.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
=> chore: add metrics for signing

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/prometheus-config/prometheus.yml
=> chore: Move metrics endpoint to separate port

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
=> chore: add vct metrics

pkg/metrics/metrics_test.go
=> fix: metrics test

cmd/orb-server/startcmd/start.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, pkg/vcsigner/signer.go, pkg/vcsigner/signer_test.go
=> chore: add signer metrics

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go, pkg/vcsigner/signer.go
=> chore: add metrics for linked data proof

test/bdd/stress_steps.go
=> chore: ignore cannot assign address in stress test

test/bdd/stress_steps.go
=> fix: stress test

test/bdd/stress_steps.go
=> chore: ignore error cannot assign requested address

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/options.go, pkg/activitypub/vocab/options_test.go, pkg/activitypub/vocab/vocab.go, pkg/anchor/writer/writer.go, test/bdd/common_steps.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/testdata/offer_activity.json, test/bdd/httpclient.go
Added a 'target' to the Offer activity and replaced 'Like' with 'Accept' offer.
closes #693
=> chore: Updated Offer/Accept according to latest spec

test/bdd/stress_steps.go
=> chore: ignore connection timed out error

cmd/orb-cli/witnesscmd/witness.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, pkg/activitypub/service/service_test.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objectproperty.go, pkg/activitypub/vocab/vocab.go, test/bdd/features/activitypub.feature, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature
=> chore: Change 'InviteWitness' to 'Invite' activity

cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/followcmd/follow_test.go, cmd/orb-cli/witnesscmd/witness.go, cmd/orb-cli/witnesscmd/witness_test.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/vocab/activitytype.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/objecttype.go, pkg/activitypub/vocab/objecttype_test.go, test/bdd/features/activitypub.feature
=> chore: Update Undo activity according to latest spec

pkg/activitypub/resthandler/outboxhandler.go, pkg/activitypub/resthandler/outboxhandler_test.go, pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/errors/errors.go, pkg/errors/errors_test.go, test/bdd/features/activitypub.feature
=> fix: Return HTTP 400 for invalid activity posted to outbox

internal/pkg/ldcontext/payload/activity-anchors-v1.json
=> chore: switch activity-anchors resourcse to @json

pkg/anchor/writer/writer.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/mocks/metricsprovider.go
=> chore: add resolve host meta link metric

pkg/metrics/metrics.go
=> fix: resolve host meta link metric

pkg/anchor/activity/activity.go, pkg/anchor/activity/activity_test.go, pkg/anchor/subject/model.go, pkg/anchor/writer/writer.go
Add support for multiple attachments in anchor.
Closes #670
=> feat: Add support for multiple attachments in anchor

cmd/orb-server/startcmd/params.go
=> fix: change default batch timeout to 1 minute

pkg/metrics/metrics.go
=> fix: Register metrics for MongoDB

test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature
Add bdd test for:
- did discovery with https hint
- for resolution with https hint
Closes #673
=> chore: Add bdd test for did discovery with https hint

pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go
=> fix: Panic when no result in Like activity

pkg/activitypub/service/activityhandler/activityhandler.go, pkg/activitypub/service/activityhandler/activityhandler_test.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/service/activityhandler/outboxhandler.go, test/bdd/common_steps.go, test/bdd/features/did-orb.feature, test/bdd/state.go
=> feat: Implement 'Undo' of a 'Like' activity

pkg/metrics/metrics.go
=> chore: remove debug msg for db time

pkg/cas/ipfs/ipfs.go
=> chore: remove ipfs content from log msg

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum
=> chore: update to latest orb vdr in orb-driver

pkg/discovery/did/local/discovery.go, pkg/discovery/did/local/discovery_test.go
=> chore: get cid from did when failed to get latest cid

cmd/orb-server/go.mod, cmd/orb-server/go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update MongoDB storage provider version

test/bdd/bddtests_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/stress_steps.go
- Create did with 6 keys
- Update did with current 6 keys and new 2 keys (this will confrim that update not sending existing keys to avoid exceeds maximum delta size)
- Add event timings for read method
=> chore: improve stress test

.github/workflows/build.yml, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/config/config.go, pkg/mocks/protocol.go, pkg/protocolversion/factoryregistry/factoryregistry.go, pkg/protocolversion/factoryregistry/factoryregistry_test.go, pkg/protocolversion/factoryregistry/mocks/protocolfactory.gen.go, pkg/protocolversion/mocks/casresolver.gen.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, pkg/store/operation/unpublished/store.go, pkg/store/operation/unpublished/store_test.go, pkg/versions/1_0/txnprocessor/txnprocessor.go, pkg/versions/1_0/txnprocessor/txnprocessor_test.go, test/bdd/did_orb_steps.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Included:
- implement update/unpublished store
- add unpublished store option to custom Orb txn handler
- update to latest sidetree-core
- BDD test to resolve updated document from update/unpublished store
Closes #759
=> feat: Add update/unpublished operation store

test/bdd/stress_steps.go
=> chore: remove measure for read method in stress test

test/bdd/stress_steps.go
=> chore: update stress test

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/store/wrapper/store.go
=> chore: add DB batch metric

pkg/metrics/metrics.go
=> fix: get batch metric

pkg/cas/resolver/resolver.go
=> fix: resolve metric

pkg/anchor/witness/proof/proof.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go
Save witness with selected flag = true if selected
Closes #934
=> chore: Save witness with selected flag = true if selected

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/bdd/go.mod, test/bdd/go.sum
Update sidetree core and add metrics for process operation.
Closes #947
=> chore: Update sidetree core and add metrics for process operation

test/bdd/stress_steps.go
=> Don't merge

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber.go, pkg/activitypub/service/inbox/httpsubscriber/httpsubscriber_test.go, pkg/activitypub/service/inbox/inbox.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/service.go, pkg/activitypub/service/service_test.go
=> fix: Don't verify HTTP signatures in inbox if auth is disabled

cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update sidetree-core-go revision

go.mod, pkg/httpserver/server.go
=> chore: configure http2 server

cmd/orb-driver/startcmd/start.go, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/inbox/inbox_test.go, pkg/activitypub/service/outbox/httppublisher/httppublisher_test.go, pkg/activitypub/service/outbox/outbox_test.go, pkg/activitypub/service/service_test.go, pkg/httpserver/server.go, pkg/httpserver/server_test.go, test/bdd/stress_steps.go
=> chore: add server idle timeout

pkg/httpserver/server.go
=> chore: add h2c to http server

cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go
A warning is logged for Reject activities received in the inbox and an Info is logged for all other activities.
closes #1023
=> feat: Log a warning for Reject activity

.github/workflows/build.yml, .github/workflows/publish.yaml, cmd/orb-cli/go.mod, cmd/orb-driver/go.mod, cmd/orb-server/go.mod, test/bdd/go.mod
=> chore: update to 1.17

.github/workflows/build.yml, .github/workflows/publish.yaml, Makefile
=> fix: publish job

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/config/config.go, pkg/orbclient/resolutionverifier/resolutionverifier_test.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
Allow update If create operation exists in unpublished store.
Closes #998
=> feat: Allow update without published create operation

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/resolvehandler/resolvehandler_test.go, pkg/document/updatehandler/updatehandler.go, pkg/document/updatehandler/updatehandler_test.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose.yml
Remove create document store and adjust BDD tests.
Closes #1038
=> chore: Remove create document store

pkg/driver/restapi/operations.go, pkg/driver/restapi/operations_test.go, test/bdd/fixtures/uni-resolver-web/config.json
=> chore: update orb driver endpoint

.gitignore, Makefile, cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/common_steps.go, test/bdd/docker_steps.go, test/bdd/features/onboard-recovery.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/utils.go
=> test: Add BDD test for backup and restore

cmd/orb-cli/main.go, cmd/orb-cli/resolvedidcmd/resolvedid.go, cmd/orb-cli/resolvedidcmd/resolvedid_test.go, test/bdd/cli_steps.go, test/bdd/features/orb-cli.feature
=> chore: add resolve DID to cli

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go
=> chore: Make host-metrics-url optional

.github/workflows/build.yml
=> chore: publish arm64 cli

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum
=> chore: update to latest orb vdr in cli

cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/client/client.go
=> fix: support http in did web in discovery client

cmd/orb-cli/acceptlistcmd/acceptlist.go, cmd/orb-cli/acceptlistcmd/getcmd.go, cmd/orb-cli/acceptlistcmd/updatecmd.go, cmd/orb-cli/createdidcmd/createdid.go, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/followcmd/follow.go, cmd/orb-cli/ipfskeygencmd/keygen.go, cmd/orb-cli/ipnshostmetagencmd/ipnshostmetagencmd.go, cmd/orb-cli/ipnshostmetauploadcmd/ipnshostmetauploadcmd.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/resolvedidcmd/resolvedid.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-cli/witnesscmd/witness.go
=> fix: add SilenceUsage for orb cli

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest orb vdr

test/bdd/did_orb_steps.go
=> fix: Use the provided URL if not found in local URL map

pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go
=> fix: Remove duplicate witness proofs from VC

pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, pkg/anchor/builder/builder.go, pkg/anchor/builder/builder_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, pkg/vcsigner/signer.go
=> fix: add jws context when sign using JsonWebSignature2020

cmd/orb-server/startcmd/params.go, pkg/activitypub/service/activityhandler/inboxhandler.go, pkg/activitypub/vocab/activitytype_test.go, pkg/activitypub/vocab/anchoreventtype_test.go, pkg/activitypub/vocab/options.go, pkg/anchor/anchorevent/anchorevent.go, pkg/anchor/anchorevent/anchorevent_test.go, pkg/anchor/handler/proof/handler.go, pkg/anchor/handler/proof/handler_test.go, pkg/anchor/writer/writer.go, pkg/anchor/writer/writer_test.go, test/bdd/common_steps.go, test/bdd/features/activitypub.feature, test/bdd/fixtures/testdata/create_activity.json
Also changed the default media type of anchor objects to application/gzip.
closes #1118
=> fix: Fixed the context on AnchorEvent objects

pkg/activitypub/httpsig/algorithm.go, test/bdd/kmssigner.go
=> fix: Set HTTP signature 'algorithm' field to Ed25519

test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose-testver.yml
=> chore: Remove unnecessary containers for versions BDD test

test/bdd/cli_steps.go
=> fix: orb driver bdd test

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go
=> chore: add keys ID config

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, test/bdd/common_steps.go, test/bdd/features/did-orb.feature, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml
=> fix: Move to single purpose orb keys

pkg/orbclient/aoprovider/anchororiginprovider.go, pkg/orbclient/aoprovider/anchororiginprovider_test.go, pkg/orbclient/protocol/nsprovider/namespaceprovider_test.go, pkg/orbclient/protocol/verprovider/versionprovider.go, pkg/orbclient/protocol/verprovider/versionprovider_test.go, pkg/orbclient/resolutionverifier/resolutionverifier.go, pkg/orbclient/resolutionverifier/resolutionverifier_test.go, scripts/integration.sh, test/bdd/did_orb_steps.go, test/bdd/features/versions.feature, test/bdd/fixtures/docker-compose-testver.yml
Add test for client versions
Closes #1163 
=> chore: Add test for client versions

cmd/orb-cli/common/common.go, cmd/orb-cli/createdidcmd/createdid_test.go, cmd/orb-cli/deactivatedidcmd/deactivatedid.go, cmd/orb-cli/deactivatedidcmd/deactivatedid_test.go, cmd/orb-cli/recoverdidcmd/recoverdid.go, cmd/orb-cli/recoverdidcmd/recoverdid_test.go, cmd/orb-cli/updatedidcmd/updatedid.go, cmd/orb-cli/updatedidcmd/updatedid_test.go, scripts/generate_test_keys.sh, test/bdd/cli_steps.go, test/bdd/features/orb-cli.feature
=> chore: add bdd test for orb cli using kms keys

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest sidetree-core-go

cmd/orb-cli/common/common.go, cmd/orb-cli/common/common_test.go, test/bdd/cli_steps.go, test/bdd/fixtures/docker-compose.yml
=> chore: support ec keys in orb-cli kms

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml
=> feat: add generic kms configuration

cmd/orb-server/go.mod, cmd/orb-server/go.sum, test/bdd/fixtures/aws-config/init/seed.yaml, test/bdd/fixtures/docker-compose.yml
=> chore: update to latest aws service

cmd/orb-server/go.mod, cmd/orb-server/go.sum, test/bdd/fixtures/docker-compose.yml
=> chore: update to latest kms

cmd/orb-server/startcmd/start.go
=> fix: Change log level for parameters to DEBUG

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
=> chore: add aws metrics

cmd/orb-server/startcmd/start.go, pkg/activitypub/service/vct/logmonitoring/monitor.go, pkg/activitypub/service/vct/logmonitoring/monitor_test.go, pkg/store/logmonitor/store.go, pkg/store/logmonitor/store_test.go
Task manager already has processing logic. Create wait group to execute domains in parallel.
Close #1196
=> chore: Remove processing flag per domain

.github/workflows/build.yml
=> chore: add sonarcloud github action step

pkg/activitypub/service/outbox/outbox.go, pkg/activitypub/service/outbox/outbox_test.go
=> feat: Resolve inbox references concurrently

.github/workflows/build.yml, .github/workflows/sonar.yml
=> chore: use sonar token

.github/workflows/sonar.yml
=> fix: projectKey in sonar

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/activitypub/service/vct/logmonitoring/monitor.go, pkg/activitypub/service/vct/logmonitoring/monitor_test.go, pkg/activitypub/service/vct/proofmonitoring/monitoring.go, pkg/activitypub/service/vct/proofmonitoring/monitoring_test.go, pkg/activitypub/service/vct/vct.go, pkg/activitypub/service/vct/vct_test.go, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> feat: add request tokens param

cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/params_test.go, cmd/orb-server/startcmd/start.go, pkg/activitypub/service/vct/logmonitoring/monitor.go, pkg/activitypub/service/vct/logmonitoring/monitor_test.go
Configure Log Monitor parameters:
- interval check
- get entries range
- max tree size for checking new log
Closes #1227
=> chore: Configure Log Monitor parameters

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core
Closes #1234
=> chore: Return deactivate operation anchoring time in "updated" field

test/bdd/cli_steps.go, test/bdd/features/orb-driver.feature
=> chore: fix orb driver bdd test

pkg/internal/testutil/rabbitmqtestutil/rabbitmqtestutil.go
=> chore: Add copyright header

.github/workflows/build.yml
=> chore: change version-fragment to vc

.github/workflows/build.yml
=> chore: fix version release

pkg/activitypub/service/outbox/outbox_test.go
=> fix: Outbox unit test failing intermittently

pkg/store/logentry/store_test.go
Add test for creating STH from retrieved log entries
Closes #1258
=> chore: Add test for creating STH from retrieved log entries

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core (service endpoint format)
Closes #1271
=> chore: Update sidetree-core (service endpoint format)

cmd/orb-server/startcmd/start.go, pkg/store/logmonitor/store.go, pkg/store/logmonitor/store_test.go, pkg/vct/logmonitoring/resthandler/retriever.go, pkg/vct/logmonitoring/resthandler/retriever_test.go, pkg/vct/logmonitoring/resthandler/update.go, pkg/vct/logmonitoring/resthandler/update_test.go, test/bdd/features/did-orb.feature
Add REST endpoint to list active, inactive logs
Closes #1285
=> feat: Add REST endpoint to list active, inactive logs

cmd/orb-cli/logcmd/getcmd.go, cmd/orb-cli/logcmd/getcmd_test.go, cmd/orb-cli/logcmd/log.go, cmd/orb-cli/logcmd/log_test.go, cmd/orb-cli/logcmd/updatecmd.go, cmd/orb-cli/logcmd/updatecmd_test.go, cmd/orb-cli/main.go, test/bdd/features/orb-cli.feature
Add configuring VCT URL to CLI
Closes #1278
=> feat: Add configuring log URL for domain to CLI

cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go
=> chore: update to latest kms aws

samples/tutorial/create_services.json, samples/tutorial/create_services2.json
=> fix: Update service endpoints in tutorial

pkg/protocolversion/versions/test/v_test/config/protocol.go, pkg/protocolversion/versions/test/v_test/config/protocol_test.go, pkg/protocolversion/versions/v1_0/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol_test.go
=> chore: change MaxOperationCount to 10000

test/bdd/stress_steps.go
=> chore: fix stress test

pkg/pubsub/amqp/amqppubsub.go
=> chore: disable mq health check

pkg/protocolversion/versions/test/v_test/config/protocol.go, pkg/protocolversion/versions/test/v_test/config/protocol_test.go, pkg/protocolversion/versions/v1_0/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol_test.go
=> Revert "chore: change MaxOperationCount to 10000"

pkg/protocolversion/versions/test/v_test/config/protocol.go, pkg/protocolversion/versions/test/v_test/config/protocol_test.go, pkg/protocolversion/versions/v1_0/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol_test.go
=> chore: change max operation size to 10000

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/.env, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to rc2 vct and sidetree-core-go

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/mocks/protocol.go, pkg/protocolversion/versions/test/v_test/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol.go, test/bdd/cli_steps.go, test/bdd/features/orb-driver.feature, test/bdd/go.mod, test/bdd/go.sum
Update sidetree-core (rename also-knonwn-as patches)
Closes #1414
=> chore: Update sidetree-core (rename also-known-as patches)

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, test/bdd/features/orb-driver.feature, test/bdd/go.mod, test/bdd/go.sum
=> chore: enable orb driver test

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/anchor/anchorlinkset/generator/didorbgenerator/didorbgenerator.go, pkg/vcsigner/signer.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: udpate to latest aires

internal/pkg/ldcontext/payload/activity-anchors-v1.json, samples/docker/contexts/ld-contexts.json, samples/tutorial/contexts/ld-contexts.json, test/bdd/fixtures/contexts/ld-contexts.json
=> chore: Update JSON-LD context for activity anchors

test/bdd/fixtures/contexts/ld-contexts.json
=> chore: update ld contexts for vct

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/start.go, cmd/orb-server/startcmd/start_test.go, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum, test/bdd/stress_steps.go
=> feat: Update Aries-Framework-Go, update Aries KMS calls

test/bdd/workerpool.go
=> chore: change log msg

cmd/orb-server/startcmd/start.go, pkg/discovery/endpoint/restapi/mocks/webresolver.gen.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/document/webresolver/resolvehandler.go, pkg/document/webresolver/resolvehandler_test.go, pkg/metrics/metrics.go, test/bdd/did_orb_steps.go, test/bdd/features/did-sidetree.feature
Included:
- Add new handle to operations for /scid/{id}/did.json
- Add cases for unpublished and deactivated to WebResolver
- Add BDD tests
Closes #1427
=> feat: Integrate did:web REST endpoint

Makefile, pkg/mocks/protocol.go, pkg/protocolversion/versions/test/v_test/config/protocol.go, pkg/protocolversion/versions/v1_0/config/protocol.go
Remove ietf-json-patch from protocol
Closes #1444
=> chore: Remove ietf-json-patch from protocol

.github/workflows/publish.yaml
=> chore: increase publish timeout

.github/workflows/build.yml
=> chore: update publish job

pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, test/bdd/features/did-sidetree.feature
Expose did:web resolver in Orb (https://orb.domain3.com/1.0/identifiers/did:web:orb.domain3.com:scid:EiAjFq0Vf_SqLZbMN5P_hpRFh891Q2rQas43XMTSsGy_qw)
Closes #1452
=> feat: Expose did:web resolver in Orb

test/bdd/fixtures/docker-compose.yml
=> chore: update go-ipfs image

cmd/orb-driver/startcmd/start.go
=> fix: orb-driver domains

cmd/orb-driver/go.mod, cmd/orb-driver/go.sum
=> chore: update vdr in orb-driver

cmd/orb-server/startcmd/start.go
=> fix: dev mode option

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, pkg/vct/logmonitoring/monitor_test.go, pkg/vct/proofmonitoring/monitoring_test.go, pkg/webfinger/client/client.go, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> fix: Change Webfinger resource ID to be the domain

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update sidetree-core-go

internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/cas/ipfs/ipfs.go, pkg/cas/resolver/resolver.go, pkg/config/client/client.go, pkg/context/opqueue/opqueue.go, pkg/context/protocol/client/client.go, pkg/discovery/did/local/discovery.go, pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/restapi/operations.go, pkg/document/remoteresolver/remoteresolver.go, pkg/document/resolvehandler/resolvehandler.go, pkg/document/updatehandler/decorator/decorator.go, pkg/document/webresolver/resolvehandler.go
Implemented structured logging for the following subsystems:
- cas
- config
- context
- discovery
- document
=> feat: Convert subsystems to use structured logs

pkg/discovery/endpoint/client/client.go, pkg/discovery/endpoint/client/client_test.go
=> chore: Add auth token provider

cmd/orb-server/startcmd/start.go, test/bdd/fixtures/docker-compose.yml
=> chore: get aws region from key ID

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, go.mod, go.sum, test/bdd/fixtures/docker-compose-testver.yml, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest sidetree-core and vct

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update orb vdr to rc4

cmd/orb-cli/go.mod, cmd/orb-cli/go.sum, cmd/orb-driver/go.mod, cmd/orb-driver/go.sum, cmd/orb-server/go.mod, cmd/orb-server/go.sum, cmd/orb-server/startcmd/params.go, cmd/orb-server/startcmd/start.go, go.mod, go.sum, pkg/document/util/util.go, pkg/protocolversion/factoryregistry/factoryregistry.go, pkg/protocolversion/factoryregistry/factoryregistry_test.go, pkg/protocolversion/factoryregistry/testversions.go, pkg/protocolversion/factoryregistry/versions.go, pkg/protocolversion/versions/v1_0/factory/factory.go, pkg/protocolversion/versions/v1_0/factory/factory_test.go, test/bdd/features/did-orb.feature, test/bdd/features/did-sidetree.feature, test/bdd/features/onboard-recovery.feature, test/bdd/features/orb-driver.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> fix: Add support for DID as an alternate source
